In [4]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!pip install -q pandas numpy scikit-learn sentence-transformers xgboost

In [6]:
import pandas
import numpy
import sklearn
import sentence_transformers
import xgboost

print("Setup successful")

Setup successful

In [7]:
PROJECT_PATH = "/content/drive/MyDrive/AI_Resume_Screening"

In [8]:
import os

os.makedirs(f"{PROJECT_PATH}/data/raw", exist_ok=True)
os.makedirs(f"{PROJECT_PATH}/data/processed", exist_ok=True)
os.makedirs(f"{PROJECT_PATH}/data/labels", exist_ok=True)
os.makedirs(f"{PROJECT_PATH}/models", exist_ok=True)
os.makedirs(f"{PROJECT_PATH}/results", exist_ok=True)

In [9]:
FEATURE_NAMES = [
    "semantic_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance",
    "keyword_overlap",
    "tfidf_similarity",
]

RANDOM_SEED = 42

LABELS = [0, 1, 2, 3]

SENTENCE_MODEL = "all-MiniLM-L6-v2"

XGBOOST_OBJECTIVE = "rank:pairwise"

In [10]:
import pandas as pd


def load_dataset(path):
    return pd.read_csv(path)


def validate_dataset(df):
    required_columns = [
        "job_id",
        "candidate_id",
        "resume_text",
        "job_text",
        "relevance_label"
    ]

    missing = [column for column in required_columns if column not in df.columns]

    if missing:
        raise ValueError(f"Missing columns: {missing}")

    if not df["relevance_label"].isin([0, 1, 2, 3]).all():
        raise ValueError("Labels must be 0, 1, 2, or 3")

    return df

In [11]:
test_data = pd.DataFrame({
    "job_id": ["J001"],
    "candidate_id": ["C001"],
    "resume_text": ["Python developer"],
    "job_text": ["Python developer required"],
    "relevance_label": [3]
})

validate_dataset(test_data)

print("Dataset validation successful")

Dataset validation successful

In [12]:
DATASET_PATH = f"{PROJECT_PATH}/data/raw/ranking_dataset.csv"

df = pd.read_csv(DATASET_PATH)

df

,job_id,candidate_id,resume_text,job_text,relevance_label
0,J001,C001,"""Python developer with 2 years of experience i...","""Machine Learning Engineer. Requires Python, m...",3
1,J001,C002,"""Frontend developer with 1 year of experience ...","""Machine Learning Engineer. Requires Python, m...",1
2,J001,C003,"""Data analyst with 2 years of experience using...","""Machine Learning Engineer. Requires Python, m...",2

In [13]:
validate_dataset(df)

print("Dataset validation successful")

Dataset validation successful

In [14]:
print("Number of jobs:", df["job_id"].nunique())
print("Number of candidates:", df["candidate_id"].nunique())
print("Number of job-candidate pairs:", len(df))

Number of jobs: 1
Number of candidates: 3
Number of job-candidate pairs: 3

In [15]:
print(df["relevance_label"].value_counts().sort_index())

relevance_label
1    1
2    1
3    1
Name: count, dtype: int64

In [16]:
group_sizes = df.groupby("job_id").size()

print(group_sizes)

job_id
J001    3
dtype: int64

In [17]:
CANDIDATES_PATH = f"{PROJECT_PATH}/data/raw/candidates.csv"

candidates_df = pd.read_csv(CANDIDATES_PATH)

candidates_df

  candidate_id                                        resume_text
0         C001  Python developer with 2 years of experience in...
1         C002  Full stack developer with 3 years of experienc...
2         C003  Data scientist with 2 years of experience in P...
3         C004  Python backend developer with 2 years of exper...
4         C005  Data analyst with 2 years of experience in SQL...
5         C006  Frontend developer with 2 years of experience ...
6         C007  Machine learning engineer with 3 years of expe...
7         C008  Software developer with 3 years of experience ...
8         C009  Data scientist with 3 years of experience in s...
9         C010  Software developer with 2 years of experience ...

In [18]:
JOBS_PATH = f"{PROJECT_PATH}/data/raw/jobs.csv"

jobs_df = pd.read_csv(JOBS_PATH)

jobs_df

,job_id,job_title,job_text
0,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...
1,J002,Data Scientist,We are looking for a Data Scientist with Pytho...
2,J003,Python Developer,We are looking for a Python Developer with str...
3,J004,Full Stack Developer,We are looking for a Full Stack Developer with...
4,J005,Data Analyst,"We are looking for a Data Analyst with SQL, Py..."

In [19]:
pairs = jobs_df.merge(candidates_df, how="cross")

pairs = pairs[
    [
        "job_id",
        "job_title",
        "job_text",
        "candidate_id",
        "resume_text"
    ]
]

print("Number of candidate-job pairs:", len(pairs))

pairs.head()

Number of candidate-job pairs: 50

,job_id,job_title,job_text,candidate_id,resume_text
0,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C001,Python developer with 2 years of experience in...
1,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C002,Full stack developer with 3 years of experienc...
2,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C003,Data scientist with 2 years of experience in P...
3,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C004,Python backend developer with 2 years of exper...
4,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C005,Data analyst with 2 years of experience in SQL...

In [20]:
pairs[pairs["job_id"] == "J001"][["job_id", "candidate_id", "job_title"]]

  job_id candidate_id                  job_title
0   J001         C001  Machine Learning Engineer
1   J001         C002  Machine Learning Engineer
2   J001         C003  Machine Learning Engineer
3   J001         C004  Machine Learning Engineer
4   J001         C005  Machine Learning Engineer
5   J001         C006  Machine Learning Engineer
6   J001         C007  Machine Learning Engineer
7   J001         C008  Machine Learning Engineer
8   J001         C009  Machine Learning Engineer
9   J001         C010  Machine Learning Engineer

In [21]:
pairs.groupby("job_id").size()

job_id
J001    10
J002    10
J003    10
J004    10
J005    10
dtype: int64

In [22]:
PAIRS_PATH = f"{PROJECT_PATH}/data/processed/candidate_job_pairs.csv"

pairs.to_csv(PAIRS_PATH, index=False)

print("Candidate-job pairs saved successfully")

Candidate-job pairs saved successfully

In [23]:
labeled_pairs = pairs.copy()

labeled_pairs["relevance_label"] = None

labeled_pairs.head()

,job_id,job_title,job_text,candidate_id,resume_text,relevance_label
0,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C001,Python developer with 2 years of experience in...,None
1,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C002,Full stack developer with 3 years of experienc...,None
2,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C003,Data scientist with 2 years of experience in P...,None
3,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C004,Python backend developer with 2 years of exper...,None
4,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C005,Data analyst with 2 years of experience in SQL...,None

In [24]:
LABELING_PATH = f"{PROJECT_PATH}/data/labels/labeled_pairs.csv"

labeled_pairs.to_csv(LABELING_PATH, index=False)

print("Labeling file created")

Labeling file created

In [25]:
LABELING_PATH = f"{PROJECT_PATH}/data/labels/labeled_pairs.csv"   #load the labelling files

labeled_pairs = pd.read_csv(LABELING_PATH)

print("Number of pairs:", len(labeled_pairs))

labeled_pairs.head()

Number of pairs: 50

,job_id,job_title,job_text,candidate_id,resume_text,relevance_label
0,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C001,Python developer with 2 years of experience in...,NaN
1,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C002,Full stack developer with 3 years of experienc...,NaN
2,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C003,Data scientist with 2 years of experience in P...,NaN
3,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C004,Python backend developer with 2 years of exper...,NaN
4,J001,Machine Learning Engineer,We are looking for a Machine Learning Engineer...,C005,Data analyst with 2 years of experience in SQL...,NaN

In [26]:
pd.set_option("display.max_colwidth", 200)

labeled_pairs[
    [
        "job_id",
        "job_title",
        "candidate_id",
        "relevance_label"
    ]
]      #inspect 50 mpairs

   job_id                  job_title candidate_id  relevance_label
0    J001  Machine Learning Engineer         C001              NaN
1    J001  Machine Learning Engineer         C002              NaN
2    J001  Machine Learning Engineer         C003              NaN
3    J001  Machine Learning Engineer         C004              NaN
4    J001  Machine Learning Engineer         C005              NaN
5    J001  Machine Learning Engineer         C006              NaN
6    J001  Machine Learning Engineer         C007              NaN
7    J001  Machine Learning Engineer         C008              NaN
8    J001  Machine Learning Engineer         C009              NaN
9    J001  Machine Learning Engineer         C010              NaN
10   J002             Data Scientist         C001              NaN
11   J002             Data Scientist         C002              NaN
12   J002             Data Scientist         C003              NaN
13   J002             Data Scientist         C004              NaN
14   J002             Data Scientist         C005              NaN
15   J002             Data Scientist         C006              NaN
16   J002             Data Scientist         C007              NaN
17   J002             Data Scientist         C008              NaN
18   J002             Data Scientist         C009              NaN
19   J002             Data Scientist         C010              NaN
20   J003           Python Developer         C001              NaN
21   J003           Python Developer         C002              NaN
22   J003           Python Developer         C003              NaN
23   J003           Python Developer         C004              NaN
24   J003           Python Developer         C005              NaN
25   J003           Python Developer         C006              NaN
26   J003           Python Developer         C007              NaN
27   J003           Python Developer         C008              NaN
28   J003           Python Developer         C009              NaN
29   J003           Python Developer         C010              NaN
30   J004       Full Stack Developer         C001              NaN
31   J004       Full Stack Developer         C002              NaN
32   J004       Full Stack Developer         C003              NaN
33   J004       Full Stack Developer         C004              NaN
34   J004       Full Stack Developer         C005              NaN
35   J004       Full Stack Developer         C006              NaN
36   J004       Full Stack Developer         C007              NaN
37   J004       Full Stack Developer         C008              NaN
38   J004       Full Stack Developer         C009              NaN
39   J004       Full Stack Developer         C010              NaN
40   J005               Data Analyst         C001              NaN
41   J005               Data Analyst         C002              NaN
42   J005               Data Analyst         C003              NaN
43   J005               Data Analyst         C004              NaN
44   J005               Data Analyst         C005              NaN
45   J005               Data Analyst         C006              NaN
46   J005               Data Analyst         C007              NaN
47   J005               Data Analyst         C008              NaN
48   J005               Data Analyst         C009              NaN
49   J005               Data Analyst         C010              NaN

In [27]:
label_map = {
    "J001": {
        "C001": 2,
        "C002": 0,
        "C003": 3,
        "C004": 1,
        "C005": 2,
        "C006": 0,
        "C007": 3,
        "C008": 0,
        "C009": 3,
        "C010": 1
    },
    "J002": {
        "C001": 2,
        "C002": 0,
        "C003": 3,
        "C004": 1,
        "C005": 3,
        "C006": 0,
        "C007": 2,
        "C008": 0,
        "C009": 3,
        "C010": 1
    },
    "J003": {
        "C001": 3,
        "C002": 1,
        "C003": 1,
        "C004": 3,
        "C005": 1,
        "C006": 0,
        "C007": 3,
        "C008": 1,
        "C009": 1,
        "C010": 2
    },
    "J004": {
        "C001": 0,
        "C002": 3,
        "C003": 0,
        "C004": 1,
        "C005": 0,
        "C006": 3,
        "C007": 0,
        "C008": 3,
        "C009": 0,
        "C010": 2
    },
    "J005": {
        "C001": 2,
        "C002": 0,
        "C003": 3,
        "C004": 0,
        "C005": 3,
        "C006": 0,
        "C007": 2,
        "C008": 0,
        "C009": 3,
        "C010": 1
    }
}

labeled_pairs["relevance_label"] = labeled_pairs.apply(
    lambda row: label_map[row["job_id"]][row["candidate_id"]],
    axis=1
)

labeled_pairs[["job_id", "candidate_id", "relevance_label"]]  #assign relevence label

   job_id candidate_id  relevance_label
0    J001         C001                2
1    J001         C002                0
2    J001         C003                3
3    J001         C004                1
4    J001         C005                2
5    J001         C006                0
6    J001         C007                3
7    J001         C008                0
8    J001         C009                3
9    J001         C010                1
10   J002         C001                2
11   J002         C002                0
12   J002         C003                3
13   J002         C004                1
14   J002         C005                3
15   J002         C006                0
16   J002         C007                2
17   J002         C008                0
18   J002         C009                3
19   J002         C010                1
20   J003         C001                3
21   J003         C002                1
22   J003         C003                1
23   J003         C004                3
24   J003         C005                1
25   J003         C006                0
26   J003         C007                3
27   J003         C008                1
28   J003         C009                1
29   J003         C010                2
30   J004         C001                0
31   J004         C002                3
32   J004         C003                0
33   J004         C004                1
34   J004         C005                0
35   J004         C006                3
36   J004         C007                0
37   J004         C008                3
38   J004         C009                0
39   J004         C010                2
40   J005         C001                2
41   J005         C002                0
42   J005         C003                3
43   J005         C004                0
44   J005         C005                3
45   J005         C006                0
46   J005         C007                2
47   J005         C008                0
48   J005         C009                3
49   J005         C010                1

In [28]:
LABELED_DATASET_PATH = f"{PROJECT_PATH}/data/labels/labeled_pairs.csv"

labeled_pairs.to_csv(LABELED_DATASET_PATH, index=False)

print("Labeled dataset saved successfully")
print("Number of rows:", len(labeled_pairs))

Labeled dataset saved successfully
Number of rows: 50

In [29]:
labeled_pairs["relevance_label"].value_counts().sort_index()

relevance_label
0    16
1    11
2     8
3    15
Name: count, dtype: int64

In [30]:
#train/validation/test
train_jobs = ["J001", "J002", "J003"]
val_jobs = ["J004"]
test_jobs = ["J005"]

train_df = labeled_pairs[labeled_pairs["job_id"].isin(train_jobs)].copy()
val_df = labeled_pairs[labeled_pairs["job_id"].isin(val_jobs)].copy()
test_df = labeled_pairs[labeled_pairs["job_id"].isin(test_jobs)].copy()

print("Training rows:", len(train_df))
print("Validation rows:", len(val_df))
print("Test rows:", len(test_df))

Training rows: 30
Validation rows: 10
Test rows: 10

In [31]:
print("Training jobs:", train_df["job_id"].unique())
print("Validation jobs:", val_df["job_id"].unique())
print("Test jobs:", test_df["job_id"].unique())  #veryfing the splits didnt overlap

Training jobs: ['J001' 'J002' 'J003']
Validation jobs: ['J004']
Test jobs: ['J005']

In [32]:
#save the datasets
train_df.to_csv(
    f"{PROJECT_PATH}/data/processed/train.csv",
    index=False
)

val_df.to_csv(
    f"{PROJECT_PATH}/data/processed/validation.csv",
    index=False
)

test_df.to_csv(
    f"{PROJECT_PATH}/data/processed/test.csv",
    index=False
)

print("Train, validation, and test datasets saved successfully")

Train, validation, and test datasets saved successfully

In [33]:
#keyword normalization function
import re

def normalize_text(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

In [34]:
def keyword_overlap(resume_text, job_text):
    resume_words = set(normalize_text(resume_text).split())
    job_words = set(normalize_text(job_text).split())

    if not job_words:
        return 0.0

    return len(resume_words & job_words) / len(job_words)
    #keyword matching

In [35]:
train_df["keyword_score"] = train_df.apply(
    lambda row: keyword_overlap(row["resume_text"], row["job_text"]),
    axis=1
)

val_df["keyword_score"] = val_df.apply(
    lambda row: keyword_overlap(row["resume_text"], row["job_text"]),
    axis=1
)

test_df["keyword_score"] = test_df.apply(
    lambda row: keyword_overlap(row["resume_text"], row["job_text"]),
    axis=1
)

test_df[
    [
        "job_id",
        "candidate_id",
        "keyword_score",
        "relevance_label"
    ]
]

   job_id candidate_id  keyword_score  relevance_label
40   J005         C001       0.393939                2
41   J005         C002       0.303030                0
42   J005         C003       0.393939                3
43   J005         C004       0.333333                0
44   J005         C005       0.606061                3
45   J005         C006       0.272727                0
46   J005         C007       0.303030                2
47   J005         C008       0.242424                0
48   J005         C009       0.363636                3
49   J005         C010       0.333333                1

In [36]:
from sklearn.metrics import ndcg_score

In [37]:
#calculate NDCG@5 on the test job
y_true = test_df["relevance_label"].to_numpy()
y_score = test_df["keyword_score"].to_numpy()

ndcg_5 = ndcg_score(
    [y_true],
    [y_score],
    k=5
)

print(f"Keyword Baseline NDCG@5: {ndcg_5:.4f}")

Keyword Baseline NDCG@5: 0.9109

In [38]:
keyword_ranking = test_df[
    ["candidate_id", "keyword_score", "relevance_label"]
].sort_values(
    "keyword_score",
    ascending=False
)

keyword_ranking

   candidate_id  keyword_score  relevance_label
44         C005       0.606061                3
40         C001       0.393939                2
42         C003       0.393939                3
48         C009       0.363636                3
49         C010       0.333333                1
43         C004       0.333333                0
41         C002       0.303030                0
46         C007       0.303030                2
45         C006       0.272727                0
47         C008       0.242424                0

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidf_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english"
)

tfidf_vectorizer.fit(
    pd.concat([
        train_df["job_text"],
        train_df["resume_text"]
    ])
)

print("TF-IDF vectorizer fitted successfully")

TF-IDF vectorizer fitted successfully

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

def tfidf_similarity(job_text, resume_text):
    job_vector = tfidf_vectorizer.transform([job_text])
    resume_vector = tfidf_vectorizer.transform([resume_text])

    return cosine_similarity(
        job_vector,
        resume_vector
    )[0][0]

In [42]:
#generate TF-IDF scores
train_df["tfidf_score"] = train_df.apply(
    lambda row: tfidf_similarity(
        row["job_text"],
        row["resume_text"]
    ),
    axis=1
)

val_df["tfidf_score"] = val_df.apply(
    lambda row: tfidf_similarity(
        row["job_text"],
        row["resume_text"]
    ),
    axis=1
)

test_df["tfidf_score"] = test_df.apply(
    lambda row: tfidf_similarity(
        row["job_text"],
        row["resume_text"]
    ),
    axis=1
)

test_df[
    [
        "job_id",
        "candidate_id",
        "tfidf_score",
        "relevance_label"
    ]
]

   job_id candidate_id  tfidf_score  relevance_label
40   J005         C001     0.125683                2
41   J005         C002     0.047258                0
42   J005         C003     0.371132                3
43   J005         C004     0.071621                0
44   J005         C005     0.881610                3
45   J005         C006     0.044535                0
46   J005         C007     0.043090                2
47   J005         C008     0.027193                0
48   J005         C009     0.317369                3
49   J005         C010     0.061993                1

In [43]:
y_true = test_df["relevance_label"].to_numpy()
y_score = test_df["tfidf_score"].to_numpy()

tfidf_ndcg_5 = ndcg_score(
    [y_true],
    [y_score],
    k=5
)

print(f"TF-IDF NDCG@5: {tfidf_ndcg_5:.4f}")

TF-IDF NDCG@5: 0.9036

In [44]:
tfidf_ranking = test_df[
    ["candidate_id", "tfidf_score", "relevance_label"]
].sort_values(
    "tfidf_score",
    ascending=False
)

tfidf_ranking

   candidate_id  tfidf_score  relevance_label
44         C005     0.881610                3
42         C003     0.371132                3
48         C009     0.317369                3
40         C001     0.125683                2
43         C004     0.071621                0
49         C010     0.061993                1
41         C002     0.047258                0
45         C006     0.044535                0
46         C007     0.043090                2
47         C008     0.027193                0

In [45]:
baseline_results = pd.DataFrame({
    "method": [
        "Keyword Overlap",
        "TF-IDF"
    ],
    "ndcg_at_5": [
        ndcg_5,
        tfidf_ndcg_5
    ]
})

baseline_results

            method  ndcg_at_5
0  Keyword Overlap   0.910927
1           TF-IDF   0.903622

In [46]:
!pip install -q sentence-transformers

In [47]:
from sentence_transformers import SentenceTransformer

In [48]:
model = SentenceTransformer("all-MiniLM-L6-v2")

print("Sentence Transformer loaded successfully")
#all-MiniLM-L6-v2 is relatively lightweight, which is useful for our Google Colab development environment.

#We are not training this transformer from scratch. We're using a pretrained sentence-embedding model to generate semantic representations.

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Sentence Transformer loaded successfully

In [49]:
#generate job embeddings
train_job_embeddings = model.encode(
    train_df["job_text"].tolist(),
    show_progress_bar=True
)

val_job_embeddings = model.encode(
    val_df["job_text"].tolist(),
    show_progress_bar=True
)

test_job_embeddings = model.encode(
    test_df["job_text"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [50]:
#generate resume embeddings
train_resume_embeddings = model.encode(
    train_df["resume_text"].tolist(),
    show_progress_bar=True
)

val_resume_embeddings = model.encode(
    val_df["resume_text"].tolist(),
    show_progress_bar=True
)

test_resume_embeddings = model.encode(
    test_df["resume_text"].tolist(),
    show_progress_bar=True
)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [51]:
#calculate semantic similarity
from sklearn.metrics.pairwise import cosine_similarity

train_df["semantic_score"] = [
    cosine_similarity(
        [job_vec],
        [resume_vec]
    )[0][0]
    for job_vec, resume_vec
    in zip(train_job_embeddings, train_resume_embeddings)
]

val_df["semantic_score"] = [
    cosine_similarity(
        [job_vec],
        [resume_vec]
    )[0][0]
    for job_vec, resume_vec
    in zip(val_job_embeddings, val_resume_embeddings)
]

test_df["semantic_score"] = [
    cosine_similarity(
        [job_vec],
        [resume_vec]
    )[0][0]
    for job_vec, resume_vec
    in zip(test_job_embeddings, test_resume_embeddings)
]

test_df[
    [
        "job_id",
        "candidate_id",
        "semantic_score",
        "relevance_label"
    ]
]

   job_id candidate_id  semantic_score  relevance_label
40   J005         C001        0.621521                2
41   J005         C002        0.446761                0
42   J005         C003        0.719367                3
43   J005         C004        0.476703                0
44   J005         C005        0.905811                3
45   J005         C006        0.377739                0
46   J005         C007        0.510215                2
47   J005         C008        0.460384                0
48   J005         C009        0.699298                3
49   J005         C010        0.530267                1

In [52]:
y_true = test_df["relevance_label"].to_numpy()
y_score = test_df["semantic_score"].to_numpy()

semantic_ndcg_5 = ndcg_score(
    [y_true],
    [y_score],
    k=5
)

print(f"Sentence Transformer NDCG@5: {semantic_ndcg_5:.4f}")

Sentence Transformer NDCG@5: 0.9518

In [53]:
semantic_ranking = test_df[
    ["candidate_id", "semantic_score", "relevance_label"]
].sort_values(
    "semantic_score",
    ascending=False
)

semantic_ranking

   candidate_id  semantic_score  relevance_label
44         C005        0.905811                3
42         C003        0.719367                3
48         C009        0.699298                3
40         C001        0.621521                2
49         C010        0.530267                1
46         C007        0.510215                2
43         C004        0.476703                0
47         C008        0.460384                0
41         C002        0.446761                0
45         C006        0.377739                0

In [54]:
baseline_results = pd.DataFrame({
    "method": [
        "Keyword Overlap",
        "TF-IDF",
        "Sentence Transformer"
    ],
    "ndcg_at_5": [
        ndcg_5,
        tfidf_ndcg_5,
        semantic_ndcg_5
    ]
})

baseline_results

                 method  ndcg_at_5
0       Keyword Overlap   0.910927
1                TF-IDF   0.903622
2  Sentence Transformer   0.951811

In [55]:
baseline_results.to_csv(
    f"{PROJECT_PATH}/data/processed/baseline_results.csv",
    index=False
)

print("Baseline comparison saved successfully")

Baseline comparison saved successfully

In [56]:
print(candidates_df.columns.tolist())

['candidate_id', 'resume_text']

In [57]:
SKILLS = [
    "python",
    "machine learning",
    "deep learning",
    "sql",
    "data analysis",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "django",
    "flask",
    "javascript",
    "react",
    "node.js",
    "html",
    "css",
    "rest api",
    "excel",
    "statistics",
    "power bi",
    "tableau"
]

In [58]:
#skills extraction fuunction
def extract_skills(text):
    text = normalize_text(text)
    return {
        skill: int(skill in text)
        for skill in SKILLS
    }

In [59]:
extract_skills(candidates_df.iloc[0]["resume_text"])

{'python': 1,
 'machine learning': 1,
 'deep learning': 0,
 'sql': 1,
 'data analysis': 1,
 'pandas': 1,
 'numpy': 1,
 'scikit-learn': 0,
 'tensorflow': 1,
 'django': 0,
 'flask': 0,
 'javascript': 0,
 'react': 0,
 'node.js': 0,
 'html': 0,
 'css': 0,
 'rest api': 0,
 'excel': 0,
 'statistics': 0,
 'power bi': 0,
 'tableau': 0}

In [60]:
def extract_job_skills(text):
    text = normalize_text(text)
    return {
        skill: int(skill in text)
        for skill in SKILLS
    }

In [61]:
extract_job_skills(jobs_df.iloc[0]["job_text"])

{'python': 1,
 'machine learning': 1,
 'deep learning': 1,
 'sql': 1,
 'data analysis': 1,
 'pandas': 1,
 'numpy': 1,
 'scikit-learn': 0,
 'tensorflow': 1,
 'django': 0,
 'flask': 0,
 'javascript': 0,
 'react': 0,
 'node.js': 0,
 'html': 0,
 'css': 0,
 'rest api': 0,
 'excel': 0,
 'statistics': 0,
 'power bi': 0,
 'tableau': 0}

In [62]:
#skills match function
def skill_match_score(resume_text, job_text):
    candidate_skills = extract_skills(resume_text)
    required_skills = extract_job_skills(job_text)

    required = sum(required_skills.values())

    if required == 0:
        return 0.0

    matched = sum(
        1
        for skill in SKILLS
        if required_skills[skill] == 1
        and candidate_skills[skill] == 1
    )

    return matched / required

In [63]:
skill_match_score(
    candidates_df.iloc[0]["resume_text"],
    jobs_df.iloc[0]["job_text"]
)

0.875

In [64]:
train_df["skill_match"] = train_df.apply(
    lambda row: skill_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

val_df["skill_match"] = val_df.apply(
    lambda row: skill_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

test_df["skill_match"] = test_df.apply(
    lambda row: skill_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

test_df[
    ["job_id", "candidate_id", "skill_match", "relevance_label"]
]

   job_id candidate_id  skill_match  relevance_label
40   J005         C001     0.428571                2
41   J005         C002     0.142857                0
42   J005         C003     0.571429                3
43   J005         C004     0.285714                0
44   J005         C005     1.000000                3
45   J005         C006     0.000000                0
46   J005         C007     0.285714                2
47   J005         C008     0.142857                0
48   J005         C009     0.571429                3
49   J005         C010     0.285714                1

In [65]:
import re

def extract_years_experience(text):
    text = text.lower()

    matches = re.findall(
        r'(\d+(?:\.\d+)?)\s*\+?\s*years?',
        text
    )

    if not matches:
        return 0.0

    return max(float(x) for x in matches)

In [66]:
extract_years_experience(
    candidates_df.iloc[0]["resume_text"]
)

2.0

In [67]:
def extract_required_experience(text):
    text = text.lower()

    matches = re.findall(
        r'(\d+(?:\.\d+)?)\s*\+?\s*years?',
        text
    )

    if not matches:
        return 0.0

    return max(float(x) for x in matches)

In [68]:
extract_required_experience(
    jobs_df.iloc[0]["job_text"]
)

0.0

In [69]:
def experience_match_score(resume_text, job_text):
    candidate_years = extract_years_experience(resume_text)
    required_years = extract_required_experience(job_text)

    if required_years == 0:
        return 1.0

    return min(candidate_years / required_years, 1.0)

In [70]:
experience_match_score(
    candidates_df.iloc[0]["resume_text"],
    jobs_df.iloc[0]["job_text"]
)

1.0

In [71]:
train_df["experience_match"] = train_df.apply(
    lambda row: experience_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

val_df["experience_match"] = val_df.apply(
    lambda row: experience_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

test_df["experience_match"] = test_df.apply(
    lambda row: experience_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

test_df[
    [
        "job_id",
        "candidate_id",
        "experience_match",
        "relevance_label"
    ]
]

   job_id candidate_id  experience_match  relevance_label
40   J005         C001               1.0                2
41   J005         C002               1.0                0
42   J005         C003               1.0                3
43   J005         C004               1.0                0
44   J005         C005               1.0                3
45   J005         C006               1.0                0
46   J005         C007               1.0                2
47   J005         C008               1.0                0
48   J005         C009               1.0                3
49   J005         C010               1.0                1

In [72]:
EDUCATION_TERMS = [
    "bachelor",
    "b.tech",
    "b.e",
    "master",
    "m.tech",
    "m.e",
    "phd",
    "computer science",
    "computer engineering",
    "information technology",
    "mathematics",
    "statistics",
    "business analytics"
]

def extract_education(text):
    text = normalize_text(text)

    return {
        term: int(term in text)
        for term in EDUCATION_TERMS
    }

In [73]:
extract_education(
    candidates_df.iloc[0]["resume_text"]
)

{'bachelor': 1,
 'b.tech': 0,
 'b.e': 0,
 'master': 0,
 'm.tech': 0,
 'm.e': 0,
 'phd': 0,
 'computer science': 1,
 'computer engineering': 0,
 'information technology': 0,
 'mathematics': 0,
 'statistics': 0,
 'business analytics': 0}

In [74]:
def extract_job_education(text):
    text = normalize_text(text)

    return {
        term: int(term in text)
        for term in EDUCATION_TERMS
    }

In [75]:
extract_job_education(
    jobs_df.iloc[0]["job_text"]
)

{'bachelor': 1,
 'b.tech': 0,
 'b.e': 0,
 'master': 0,
 'm.tech': 0,
 'm.e': 0,
 'phd': 0,
 'computer science': 1,
 'computer engineering': 1,
 'information technology': 0,
 'mathematics': 1,
 'statistics': 0,
 'business analytics': 0}

In [76]:
def education_match_score(resume_text, job_text):
    candidate_education = extract_education(resume_text)
    required_education = extract_job_education(job_text)

    required = [
        term for term in EDUCATION_TERMS
        if required_education[term] == 1
    ]

    if not required:
        return 1.0

    matched = sum(
        1
        for term in required
        if candidate_education[term] == 1
    )

    return matched / len(required)

In [77]:
education_match_score(
    candidates_df.iloc[0]["resume_text"],
    jobs_df.iloc[0]["job_text"]
)

0.5

In [78]:
train_df["education_match"] = train_df.apply(
    lambda row: education_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

val_df["education_match"] = val_df.apply(
    lambda row: education_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

test_df["education_match"] = test_df.apply(
    lambda row: education_match_score(
        row["resume_text"],
        row["job_text"]
    ),
    axis=1
)

test_df[
    [
        "job_id",
        "candidate_id",
        "education_match",
        "relevance_label"
    ]
]

   job_id candidate_id  education_match  relevance_label
40   J005         C001             0.50                2
41   J005         C002             0.50                0
42   J005         C003             0.50                3
43   J005         C004             0.50                0
44   J005         C005             0.75                3
45   J005         C006             0.50                0
46   J005         C007             0.25                2
47   J005         C008             0.25                0
48   J005         C009             0.25                3
49   J005         C010             0.50                1

In [79]:
test_df[
    [
        "candidate_id",
        "skill_match",
        "experience_match",
        "education_match",
        "relevance_label"
    ]
]

,candidate_id,skill_match,experience_match,education_match,relevance_label
40,C001,0.428571,1.0,0.50,2
41,C002,0.142857,1.0,0.50,0
42,C003,0.571429,1.0,0.50,3
43,C004,0.285714,1.0,0.50,0
44,C005,1.000000,1.0,0.75,3
45,C006,0.000000,1.0,0.50,0
46,C007,0.285714,1.0,0.25,2
47,C008,0.142857,1.0,0.25,0
48,C009,0.571429,1.0,0.25,3
49,C010,0.285714,1.0,0.50,1

In [80]:
feature_columns = [
    "keyword_score",
    "tfidf_score",
    "semantic_score",
    "skill_match",
    "experience_match",
    "education_match"
]

test_df[
    ["job_id", "candidate_id"] + feature_columns + ["relevance_label"]
]

,job_id,candidate_id,keyword_score,tfidf_score,semantic_score,skill_match,experience_match,education_match,relevance_label
40,J005,C001,0.393939,0.125683,0.621521,0.428571,1.0,0.50,2
41,J005,C002,0.303030,0.047258,0.446761,0.142857,1.0,0.50,0
42,J005,C003,0.393939,0.371132,0.719367,0.571429,1.0,0.50,3
43,J005,C004,0.333333,0.071621,0.476703,0.285714,1.0,0.50,0
44,J005,C005,0.606061,0.881610,0.905811,1.000000,1.0,0.75,3
45,J005,C006,0.272727,0.044535,0.377739,0.000000,1.0,0.50,0
46,J005,C007,0.303030,0.043090,0.510215,0.285714,1.0,0.25,2
47,J005,C008,0.242424,0.027193,0.460384,0.142857,1.0,0.25,0
48,J005,C009,0.363636,0.317369,0.699298,0.571429,1.0,0.25,3
49,J005,C010,0.333333,0.061993,0.530267,0.285714,1.0,0.50,1

In [81]:
feature_columns = [
    "keyword_score",
    "tfidf_score",
    "semantic_score",
    "skill_match",
    "experience_match",
    "education_match"
]

X_train = train_df[feature_columns]
y_train = train_df["relevance_label"]

X_val = val_df[feature_columns]
y_val = val_df["relevance_label"]

X_test = test_df[feature_columns]
y_test = test_df["relevance_label"]

In [82]:
print("X_train:", X_train.shape)
print("X_val:", X_val.shape)
print("X_test:", X_test.shape)

X_train: (30, 6)
X_val: (10, 6)
X_test: (10, 6)

In [83]:
X_train.head()

,keyword_score,tfidf_score,semantic_score,skill_match,experience_match,education_match
0,0.555556,0.498967,0.817733,0.875,1.0,0.50
1,0.277778,0.067478,0.546767,0.125,1.0,0.50
2,0.416667,0.332698,0.733904,0.750,1.0,0.25
3,0.305556,0.097644,0.549058,0.250,1.0,0.50
4,0.305556,0.108400,0.632322,0.375,1.0,0.25

In [84]:
train_groups = train_df.groupby("job_id").size().tolist()
val_groups = val_df.groupby("job_id").size().tolist()
test_groups = test_df.groupby("job_id").size().tolist()

print("Train groups:", train_groups)
print("Validation groups:", val_groups)
print("Test groups:", test_groups)

Train groups: [10, 10, 10]
Validation groups: [10]
Test groups: [10]

In [85]:
print(train_df["job_id"].value_counts().sort_index())

job_id
J001    10
J002    10
J003    10
Name: count, dtype: int64

In [86]:
!pip install -q xgboost

In [87]:
from xgboost import XGBRanker

print("XGBoost Ranker loaded successfully")

XGBoost Ranker loaded successfully

In [88]:
train_qid = train_df["job_id"].astype("category").cat.codes
val_qid = val_df["job_id"].astype("category").cat.codes
test_qid = test_df["job_id"].astype("category").cat.codes
#should know which rows belongs to the same job

In [89]:
ranker = XGBRanker(
    objective="rank:ndcg",
    eval_metric="ndcg@5",
    n_estimators=100,
    learning_rate=0.05,
    max_depth=4,
    random_state=42
)

print("XGBoost Ranker created successfully")

XGBoost Ranker created successfully

In [90]:
#training the ranking model
ranker.fit(
    X_train,
    y_train,
    qid=train_qid,
    eval_set=[
        (X_val, y_val)
    ],
    eval_qid=[
        val_qid
    ],
    verbose=False
)

print("XGBoost ranking model trained successfully")

XGBoost ranking model trained successfully

In [91]:
#ranking prediction
xgb_scores = ranker.predict(X_test)

test_df["xgb_score"] = xgb_scores

test_df[
    [
        "job_id",
        "candidate_id",
        "xgb_score",
        "relevance_label"
    ]
]

   job_id candidate_id  xgb_score  relevance_label
40   J005         C001  -0.145516                2
41   J005         C002  -1.387326                0
42   J005         C003   1.381471                3
43   J005         C004  -1.089407                0
44   J005         C005   0.921994                3
45   J005         C006  -1.387326                0
46   J005         C007  -1.310142                2
47   J005         C008  -1.387326                0
48   J005         C009  -0.106697                3
49   J005         C010  -1.089407                1

In [92]:
xgb_ndcg_5 = ndcg_score(
    [test_df["relevance_label"].to_numpy()],
    [test_df["xgb_score"].to_numpy()],
    k=5
)

print(f"XGBoost Ranker NDCG@5: {xgb_ndcg_5:.4f}")

XGBoost Ranker NDCG@5: 0.9277

In [93]:
final_comparison = pd.DataFrame({
    "method": [
        "Keyword Overlap",
        "TF-IDF",
        "Sentence Transformer",
        "XGBoost Ranker"
    ],
    "ndcg_at_5": [
        ndcg_5,
        tfidf_ndcg_5,
        semantic_ndcg_5,
        xgb_ndcg_5
    ]
})

final_comparison

                 method  ndcg_at_5
0       Keyword Overlap   0.910927
1                TF-IDF   0.903622
2  Sentence Transformer   0.951811
3        XGBoost Ranker   0.927717

In [94]:
final_comparison.to_csv(
    f"{PROJECT_PATH}/data/processed/final_model_comparison.csv",
    index=False
)

print("Final model comparison saved successfully")

Final model comparison saved successfully

In [ ]:
MODEL_PATH = f"{PROJECT_PATH}/models/xgboost_ranker.json"

ranker.save_model(MODEL_PATH)

print("XGBoost model saved successfully")

In [ ]:
import os

print(os.path.exists(MODEL_PATH))

In [ ]:
def create_features(job_text, resume_text):
    keyword_score = keyword_overlap(
        resume_text,
        job_text
    )

    tfidf_score = tfidf_similarity(
        job_text,
        resume_text
    )

    job_embedding = model.encode([job_text])
    resume_embedding = model.encode([resume_text])

    semantic_score = cosine_similarity(
        job_embedding,
        resume_embedding
    )[0][0]

    skill_match = skill_match_score(
        resume_text,
        job_text
    )

    experience_match = experience_match_score(
        resume_text,
        job_text
    )

    education_match = education_match_score(
        resume_text,
        job_text
    )

    return [
        keyword_score,
        tfidf_score,
        semantic_score,
        skill_match,
        experience_match,
        education_match
    ]

In [ ]:
features = create_features(
    jobs_df.iloc[0]["job_text"],
    candidates_df.iloc[0]["resume_text"]
)

print(features)

In [ ]:
import numpy as np

feature_array = np.array(features).reshape(1, -1)

candidate_score = ranker.predict(feature_array)[0]

print("Candidate ranking score:", candidate_score)

In [ ]:
#rank multiple candidates for one job
def rank_candidates(job_text, candidates):
    results = []

    for _, candidate in candidates.iterrows():
        features = create_features(
            job_text,
            candidate["resume_text"]
        )

        feature_array = np.array(features).reshape(1, -1)

        score = ranker.predict(feature_array)[0]

        results.append({
            "candidate_id": candidate["candidate_id"],
            "score": score
        })

    results_df = pd.DataFrame(results)

    results_df = results_df.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    results_df["rank"] = results_df.index + 1

    return results_df[
        ["rank", "candidate_id", "score"]
    ]

In [ ]:
job_text = jobs_df.iloc[0]["job_text"]

ranking = rank_candidates(
    job_text,
    candidates_df
)

ranking

In [ ]:
#screeinig evidence

In [ ]:
def get_skill_evidence(resume_text, job_text):
    candidate_skills = extract_skills(resume_text)
    required_skills = extract_job_skills(job_text)

    matched = [
        skill
        for skill in SKILLS
        if required_skills[skill] == 1
        and candidate_skills[skill] == 1
    ]

    missing = [
        skill
        for skill in SKILLS
        if required_skills[skill] == 1
        and candidate_skills[skill] == 0
    ]

    return matched, missing

In [ ]:
matched, missing = get_skill_evidence(
    candidates_df.iloc[0]["resume_text"],
    jobs_df.iloc[0]["job_text"]
)

print("Matched skills:", matched)
print("Missing skills:", missing)

In [ ]:
def rank_candidates_with_evidence(job_text, candidates):
    results = []

    for _, candidate in candidates.iterrows():
        features = create_features(
            job_text,
            candidate["resume_text"]
        )

        feature_array = np.array(features).reshape(1, -1)

        score = ranker.predict(feature_array)[0]

        matched, missing = get_skill_evidence(
            candidate["resume_text"],
            job_text
        )

        results.append({
            "candidate_id": candidate["candidate_id"],
            "score": score,
            "skill_match": features[3],
            "experience_match": features[4],
            "education_match": features[5],
            "matched_skills": ", ".join(matched),
            "missing_skills": ", ".join(missing)
        })

    results_df = pd.DataFrame(results)

    results_df = results_df.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    results_df["rank"] = results_df.index + 1

    return results_df[
        [
            "rank",
            "candidate_id",
            "score",
            "skill_match",
            "experience_match",
            "education_match",
            "matched_skills",
            "missing_skills"
        ]
    ]

In [ ]:
job_text = jobs_df.iloc[0]["job_text"]

detailed_ranking = rank_candidates_with_evidence(
    job_text,
    candidates_df
)

detailed_ranking

In [ ]:
import os

os.makedirs(
    f"{PROJECT_PATH}/models",
    exist_ok=True
)

print("Models directory ready")

In [ ]:
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

print(EMBEDDING_MODEL_NAME)

In [ ]:
import joblib

TFIDF_PATH = f"{PROJECT_PATH}/models/tfidf_vectorizer.pkl"

joblib.dump(
    tfidf_vectorizer,
    TFIDF_PATH
)

print("TF-IDF vectorizer saved successfully")

In [ ]:
CONFIG_PATH = f"{PROJECT_PATH}/models/model_config.pkl"

model_config = {
    "embedding_model": EMBEDDING_MODEL_NAME,
    "feature_columns": feature_columns,
    "skills": SKILLS,
    "education_terms": EDUCATION_TERMS
}

joblib.dump(
    model_config,
    CONFIG_PATH
)

print("Model configuration saved successfully")

In [ ]:
new_job = """
Machine Learning Engineer

Requirements:
- Python
- Machine Learning
- SQL
- Pandas
- Scikit-learn
- Bachelor's degree in Computer Science
- Experience with data analysis
"""

In [ ]:
new_resume = """
Software Developer with 2 years of experience.

Skills:
Python, SQL, Pandas, Scikit-learn, JavaScript.

Experience:
Developed data processing applications using Python and SQL.
Worked on data analysis projects and built machine learning models.

Education:
Bachelor's degree in Computer Science.
"""

In [ ]:
new_features = create_features(
    new_job,
    new_resume
)

print(new_features)

In [ ]:
new_score = ranker.predict(
    np.array(new_features).reshape(1, -1)
)[0]

print("New candidate ranking score:", new_score)

In [ ]:
new_candidates = pd.DataFrame({
    "candidate_id": ["NEW_C001", "NEW_C002", "NEW_C003"],
    "resume_text": [
        """
        Machine Learning Engineer with 3 years of experience.
        Strong skills in Python, Machine Learning, SQL, Pandas,
        Scikit-learn and data analysis.
        Bachelor's degree in Computer Science.
        Developed and deployed machine learning models.
        """,

        """
        Frontend Developer with 2 years of experience.
        Skills include JavaScript, React, HTML and CSS.
        Bachelor's degree in Information Technology.
        Developed web applications and user interfaces.
        """,

        """
        Python Developer with 2 years of experience.
        Strong skills in Python, SQL and Pandas.
        Worked on data analysis and machine learning projects.
        Bachelor's degree in Computer Science.
        """
    ]
})

In [ ]:
new_ranking = rank_candidates_with_evidence(
    new_job,
    new_candidates
)

new_ranking

In [ ]:
#eveluation function NDCG AND MRR

In [ ]:
from sklearn.metrics import ndcg_score
import numpy as np

def evaluate_ranking(y_true, scores, k=5):
    y_true = np.asarray(y_true)
    scores = np.asarray(scores)

    ndcg = ndcg_score(
        [y_true],
        [scores],
        k=k
    )

    ranked_indices = np.argsort(scores)[::-1]

    mrr = 0.0

    for rank, index in enumerate(ranked_indices, start=1):
        if y_true[index] > 0:
            mrr = 1.0 / rank
            break

    return ndcg, mrr

In [ ]:
#EVELUATING XGboost MODEL
xgb_ndcg, xgb_mrr = evaluate_ranking(
    y_test,
    xgb_scores,
    k=5
)

print(f"XGBoost NDCG@5: {xgb_ndcg:.4f}")
print(f"XGBoost MRR: {xgb_mrr:.4f}")

In [ ]:
#evaluating all three baseline models
keyword_ndcg, keyword_mrr = evaluate_ranking(
    y_test,
    test_df["keyword_score"],
    k=5
)

tfidf_ndcg, tfidf_mrr = evaluate_ranking(
    y_test,
    test_df["tfidf_score"],
    k=5
)

semantic_ndcg, semantic_mrr = evaluate_ranking(
    y_test,
    test_df["semantic_score"],
    k=5
)

print(f"Keyword     - NDCG@5: {keyword_ndcg:.4f}, MRR: {keyword_mrr:.4f}")
print(f"TF-IDF      - NDCG@5: {tfidf_ndcg:.4f}, MRR: {tfidf_mrr:.4f}")
print(f"Semantic    - NDCG@5: {semantic_ndcg:.4f}, MRR: {semantic_mrr:.4f}")
print(f"XGBoost     - NDCG@5: {xgb_ndcg:.4f}, MRR: {xgb_mrr:.4f}")

In [ ]:
evaluation_results = pd.DataFrame({
    "method": [
        "Keyword",
        "TF-IDF",
        "Sentence Transformer",
        "XGBoost Ranker"
    ],
    "NDCG@5": [
        keyword_ndcg,
        tfidf_ndcg,
        semantic_ndcg,
        xgb_ndcg
    ],
    "MRR": [
        keyword_mrr,
        tfidf_mrr,
        semantic_mrr,
        xgb_mrr
    ]
})

evaluation_results

In [ ]:
evaluation_results.to_csv(
    f"{PROJECT_PATH}/data/processed/evaluation_results.csv",
    index=False
)

print("Evaluation results saved successfully")

In [ ]:
structured_scores = (
    test_df["skill_match"] +
    test_df["experience_match"] +
    test_df["education_match"]
) / 3

structured_ndcg, structured_mrr = evaluate_ranking(
    y_test,
    structured_scores,
    k=5
)

print(f"Structured Features - NDCG@5: {structured_ndcg:.4f}")
print(f"Structured Features - MRR: {structured_mrr:.4f}")

In [ ]:
sbert_structured_scores = (
    0.5 * test_df["semantic_score"] +
    0.5 * structured_scores
)

sbert_structured_ndcg, sbert_structured_mrr = evaluate_ranking(
    y_test,
    sbert_structured_scores,
    k=5
)

print(
    f"SBERT + Structured Features - "
    f"NDCG@5: {sbert_structured_ndcg:.4f}"
)

print(
    f"SBERT + Structured Features - "
    f"MRR: {sbert_structured_mrr:.4f}"
)

In [ ]:
ablation_results = pd.DataFrame({
    "method": [
        "Keyword",
        "TF-IDF",
        "Sentence Transformer",
        "Structured Features",
        "SBERT + Structured Features",
        "XGBoost Ranker"
    ],
    "NDCG@5": [
        keyword_ndcg,
        tfidf_ndcg,
        semantic_ndcg,
        structured_ndcg,
        sbert_structured_ndcg,
        xgb_ndcg
    ],
    "MRR": [
        keyword_mrr,
        tfidf_mrr,
        semantic_mrr,
        structured_mrr,
        sbert_structured_mrr,
        xgb_mrr
    ]
})

ablation_results

In [ ]:
ablation_results.to_csv(
    f"{PROJECT_PATH}/data/processed/ablation_results.csv",
    index=False
)

print("Ablation results saved successfully")

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.bar(
    ablation_results["method"],
    ablation_results["NDCG@5"]
)

plt.ylabel("NDCG@5")
plt.xlabel("Method")
plt.title("Ablation Study - NDCG@5")
plt.xticks(rotation=30, ha="right")
plt.ylim(0, 1)

plt.tight_layout()
plt.show()

In [ ]:
print(ranker.get_params())

In [ ]:
print([x for x in globals().keys() if "qid" in x.lower() or "group" in x.lower()])

In [ ]:
pairwise_ranker = XGBRanker(
    objective="rank:pairwise",
    eval_metric="ndcg@5",
    n_estimators=100,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    enable_categorical=True
)

pairwise_ranker.fit(
    X_train,
    y_train,
    qid=train_qid
)

pairwise_scores = pairwise_ranker.predict(X_test)

pairwise_ndcg, pairwise_mrr = evaluate_ranking(
    y_test,
    pairwise_scores,
    k=5
)

print(f"Pairwise XGBoost NDCG@5: {pairwise_ndcg:.4f}")
print(f"Pairwise XGBoost MRR: {pairwise_mrr:.4f}")

In [ ]:
#test deeper xgboost model
depth6_ranker = XGBRanker(
    objective="rank:ndcg",
    eval_metric="ndcg@5",
    n_estimators=100,
    learning_rate=0.05,
    max_depth=6,
    random_state=42,
    enable_categorical=True
)

depth6_ranker.fit(
    X_train,
    y_train,
    qid=train_qid
)

depth6_scores = depth6_ranker.predict(X_test)

depth6_ndcg, depth6_mrr = evaluate_ranking(
    y_test,
    depth6_scores,
    k=5
)

print(f"Depth 6 XGBoost NDCG@5: {depth6_ndcg:.4f}")
print(f"Depth 6 XGBoost MRR: {depth6_mrr:.4f}")

In [ ]:
trees200_ranker = XGBRanker(
    objective="rank:ndcg",
    eval_metric="ndcg@5",
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    enable_categorical=True
)

trees200_ranker.fit(
    X_train,
    y_train,
    qid=train_qid
)

trees200_scores = trees200_ranker.predict(X_test)

trees200_ndcg, trees200_mrr = evaluate_ranking(
    y_test,
    trees200_scores,
    k=5
)

print(f"200 Trees XGBoost NDCG@5: {trees200_ndcg:.4f}")
print(f"200 Trees XGBoost MRR: {trees200_mrr:.4f}")

In [ ]:
tuning_results = pd.DataFrame({
    "configuration": [
        "Baseline rank:ndcg",
        "rank:pairwise",
        "max_depth=6",
        "n_estimators=200"
    ],
    "NDCG@5": [
        xgb_ndcg,
        pairwise_ndcg,
        depth6_ndcg,
        trees200_ndcg
    ],
    "MRR": [
        xgb_mrr,
        pairwise_mrr,
        depth6_mrr,
        trees200_mrr
    ]
})

tuning_results

In [ ]:
tuning_results.to_csv(
    f"{PROJECT_PATH}/data/processed/tuning_results.csv",
    index=False
)

print("Tuning results saved successfully")

In [ ]:
#sanity test case
easy_job = """
Machine Learning Engineer

Requirements:
Python, Machine Learning, SQL, Pandas,
Scikit-learn, Bachelor's degree in Computer Science,
2 years of experience.
"""

easy_resume = """
Machine Learning Engineer with 3 years of experience.
Expert in Python, Machine Learning, SQL, Pandas and Scikit-learn.
Bachelor's degree in Computer Science.
"""

hard_resume = """
Graphic Designer with 4 years of experience.
Expert in Photoshop, Illustrator, branding and visual design.
Bachelor's degree in Fine Arts.
"""

partial_resume = """
Python Developer with 2 years of experience.
Strong skills in Python and SQL.
Bachelor's degree in Computer Science.
Worked on software development projects.
"""

In [ ]:
#strong smt
easy_features = create_features(
    easy_job,
    easy_resume
)

print("Easy Match Features:")
print(easy_features)

In [ ]:
#weak smt
hard_features = create_features(
    easy_job,
    hard_resume
)

print("Hard Match Features:")
print(hard_features)

In [ ]:
#partial match sanity test
partial_features = create_features(
    easy_job,
    partial_resume
)

print("Partial Match Features:")
print(partial_features)

In [ ]:
sanity_features = pd.DataFrame(
    [
        easy_features,
        partial_features,
        hard_features
    ],
    columns=feature_columns
)

sanity_scores = ranker.predict(sanity_features)

sanity_results = pd.DataFrame({
    "candidate": [
        "Strong Match",
        "Partial Match",
        "Weak Match"
    ],
    "xgboost_score": sanity_scores
})

sanity_results = sanity_results.sort_values(
    "xgboost_score",
    ascending=False
).reset_index(drop=True)

sanity_results

In [ ]:
sanity_results.to_csv(
    f"{PROJECT_PATH}/data/processed/sanity_test_results.csv",
    index=False
)

print("Sanity test results saved successfully")

In [ ]:
# @title
print("Feature columns:")
for i, col in enumerate(feature_columns, start=1):
    print(f"{i}. {col}")

In [ ]:
importance = ranker.feature_importances_

feature_importance_df = pd.DataFrame({
    "feature": feature_columns,
    "importance": importance
}).sort_values(
    "importance",
    ascending=False
).reset_index(drop=True)

feature_importance_df

In [ ]:
plt.figure(figsize=(9, 5))

plt.barh(
    feature_importance_df["feature"],
    feature_importance_df["importance"]
)

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("XGBoost Feature Importance")

plt.tight_layout()
plt.show()

In [ ]:
feature_importance_df.to_csv(
    f"{PROJECT_PATH}/data/processed/feature_importance.csv",
    index=False
)

print("Feature importance saved successfully")

In [ ]:
print(pairs.columns.tolist())

In [ ]:
[x for x in globals().keys() if "rank" in x.lower() or "result" in x.lower()]

In [ ]:
print("detailed_ranking columns:")
print(detailed_ranking.columns.tolist())

print("\nnew_ranking columns:")
print(new_ranking.columns.tolist())

In [ ]:
detailed_ranking

In [ ]:
scores = detailed_ranking["score"].to_numpy()

print("Scores:")
print(scores)

print("\nScores sorted descending:")
print(all(scores[i] >= scores[i + 1] for i in range(len(scores) - 1)))

In [ ]:
detailed_ranking[
    [
        "rank",
        "candidate_id",
        "score",
        "matched_skills",
        "missing_skills"
    ]
]

In [ ]:
detailed_ranking[
    [
        "rank",
        "candidate_id",
        "score",
        "skill_match",
        "experience_match",
        "education_match",
        "matched_skills",
        "missing_skills"
    ]
]

In [ ]:
detailed_ranking.to_csv(
    f"{PROJECT_PATH}/data/processed/final_ranking_preview.csv",
    index=False
)

print("Final ranking preview saved successfully")

In [ ]:
member2_summary = pd.DataFrame({
    "component": [
        "Keyword baseline",
        "TF-IDF baseline",
        "Sentence Transformer baseline",
        "Structured features",
        "SBERT + structured features",
        "XGBoost Ranker",
        "NDCG@5 evaluation",
        "MRR evaluation",
        "Feature importance",
        "Sanity testing",
        "Ranking explanations"
    ],
    "status": ["Completed"] * 11
})

member2_summary.to_csv(
    f"{PROJECT_PATH}/data/processed/member2_summary.csv",
    index=False
)

print("Member 2 summary saved successfully")

In [ ]:
import inspect

print(inspect.signature(rank_candidates_with_evidence))
print(inspect.getsource(rank_candidates_with_evidence))

In [ ]:
print(type(ranker))
print(ranker)

In [ ]:
[x for x in globals().keys()
 if any(word in x.lower() for word in ["model", "ranker", "joblib", "pickle"])]

In [ ]:
!git --version

In [ ]:
!git clone https://github.com/sanskar-paudel/AI-ML-Resume-Screening-Ranking-System.git

In [ ]:
%cd AI-ML-Resume-Screening-Ranking-System

In [ ]:
!ls

In [ ]:
!git config --global user.name "sanskar-paudel"
!git config --global user.email "23053609@kiit.ac.in"

In [ ]:
!git config --global user.name
!git config --global user.email

In [ ]:
!git remote -v

In [ ]:
from google.colab import userdata

token = userdata.get('GIT_HUB_TOKEN')
print("GitHub token loaded:", token is not None)

In [ ]:
from google.colab import userdata

token = userdata.get('GIT_HUB_TOKEN')

!git remote set-url origin https://sanskar-paudel:{token}@github.com/sanskar-paudel/AI-ML-Resume-Screening-Ranking-System.git

In [ ]:
!git status

In [ ]:
!ls -la

In [ ]:
import os

project_path = "/content/drive/MyDrive/AI_Resume_Screening"

for root, dirs, files in os.walk(project_path):
    level = root.replace(project_path, "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")
    for file in files:
        print(f"{indent}  {file}")

In [ ]:
!mkdir -p notebooks

In [ ]:
!mv AI_Resume_ML_Ranking.ipynb notebooks/

In [ ]:
!find . -maxdepth 2 -type f

In [ ]:
!git status

In [ ]:
!find /content/drive/MyDrive -name "*.ipynb" 2>/dev/null

In [ ]:
!cp "/content/drive/MyDrive/Colab Notebooks/AI_Resume_ML_Ranking.ipynb" "./notebooks/"

In [ ]:
!ls -lh notebooks/

In [ ]:
!git status

In [ ]:
!git add -A

In [ ]:
!git status

In [ ]:
!git commit -m "Organize ML ranking notebook"

In [ ]:
!git push origin main

In [ ]:
print("create_features exists:", "create_features" in globals())
print("rank_candidates_with_evidence exists:", "rank_candidates_with_evidence" in globals())

In [ ]:
import inspect

print(inspect.getsource(create_features))

In [ ]:
import inspect

print("=== skill_match_score ===")
print(inspect.getsource(skill_match_score))

print("\n=== experience_match_score ===")
print(inspect.getsource(experience_match_score))

print("\n=== education_match_score ===")
print(inspect.getsource(education_match_score))

In [ ]:
import inspect

print("=== extract_job_skills ===")
print(inspect.getsource(extract_job_skills))

print("\n=== extract_skills ===")
print(inspect.getsource(extract_skills))

In [ ]:
import inspect

print("=== keyword_overlap ===")
print(inspect.getsource(keyword_overlap))

print("\n=== tfidf_similarity ===")
print(inspect.getsource(tfidf_similarity))

print("\n=== extract_years_experience ===")
print(inspect.getsource(extract_years_experience))

print("\n=== extract_required_experience ===")
print(inspect.getsource(extract_required_experience))

In [ ]:
print("ranker type:", type(ranker))
print("ranker parameters:")
print(ranker.get_params())

In [ ]:
import inspect

print(inspect.getsource(rank_candidates))

In [ ]:

# MEMBER 3 → MEMBER 2 INTERFACE


def build_ml_input(job_profile, candidate_profile):
    """
    Converts Member 3 NLP outputs into a simple dictionary
    that Member 2 feature engineering can use.
    """

    return {
        "job": {
            "required_skills": job_profile.required_skills,
            "preferred_skills": job_profile.preferred_skills,
            "minimum_experience": job_profile.minimum_experience,
            "education": job_profile.education,
            "responsibilities": job_profile.responsibilities
        },

        "candidate": {
            "skills": candidate_profile.skills,
            "education": candidate_profile.education,
            "experience": candidate_profile.experience,
            "projects": candidate_profile.projects,
            "certifications": candidate_profile.certifications
        }
    }


print("Member 3 → Member 2 interface created successfully.")

In [ ]:

# MEMBER 3 → MEMBER 2 ADAPTER
# Converts Member 3 structured profiles into ML-ready input


def build_ml_input(job_profile, candidate_profile):
    """
    Convert Member 3's JobProfile and CandidateProfile objects
    into a consistent dictionary for Member 2 feature engineering.
    """

    return {
        "job": {
            "job_id": job_profile.job_id,
            "required_skills": list(job_profile.required_skills),
            "preferred_skills": list(job_profile.preferred_skills),
            "minimum_experience": float(job_profile.minimum_experience),
            "education": list(job_profile.education),
            "responsibilities": list(job_profile.responsibilities)
        },

        "candidate": {
            "candidate_id": candidate_profile.candidate_id,
            "skills": list(candidate_profile.skills),
            "education": list(candidate_profile.education),
            "experience": list(candidate_profile.experience),
            "projects": list(candidate_profile.projects),
            "certifications": list(candidate_profile.certifications)
        }
    }


print("Member 3 → Member 2 adapter created successfully.")

In [ ]:

# TEST MEMBER 3 → MEMBER 2 ADAPTER


print("Adapter function exists:", "build_ml_input" in globals())

print("\nJobProfile fields expected:")
print([
    "job_id",
    "required_skills",
    "preferred_skills",
    "minimum_experience",
    "education",
    "responsibilities"
])

print("\nCandidateProfile fields expected:")
print([
    "candidate_id",
    "skills",
    "education",
    "experience",
    "projects",
    "certifications"
])

print("\nAdapter is ready for integration.")

In [ ]:

# TEST THE MEMBER 3 → MEMBER 2 DATA STRUCTURE


from types import SimpleNamespace

# Sample Member 3-style JobProfile
test_job = SimpleNamespace(
    job_id="JOB_TEST",
    required_skills=["python", "sql"],
    preferred_skills=["machine learning"],
    minimum_experience=2.0,
    education=["bachelor"],
    responsibilities=[
        "Develop software applications",
        "Analyze data"
    ]
)

# Sample Member 3-style CandidateProfile
test_candidate = SimpleNamespace(
    candidate_id="CAND_TEST",
    skills=["python", "sql", "machine learning"],
    education=["bachelor of technology"],
    experience=[
        {"page": 1, "text": "Software Developer with 3 years of experience"}
    ],
    projects=[
        {"page": 2, "text": "Machine learning based resume screening project"}
    ],
    certifications=[
        {"page": 3, "text": "Python certification"}
    ]
)

# Convert using our adapter
test_ml_input = build_ml_input(test_job, test_candidate)

# Display the result
print("Adapter test successful.\n")

print("JOB:")
for key, value in test_ml_input["job"].items():
    print(f"{key}: {value}")

print("\nCANDIDATE:")
for key, value in test_ml_input["candidate"].items():
    print(f"{key}: {value}")

In [ ]:
# FEATURE 1: SEMANTIC SIMILARITY


def calculate_semantic_similarity(job_text, resume_text):
    """
    Calculate semantic similarity between the job description
    and candidate resume using the existing Sentence Transformer model.
    """

    job_embedding = model.encode([job_text])
    resume_embedding = model.encode([resume_text])

    similarity = cosine_similarity(
        job_embedding,
        resume_embedding
    )[0][0]

    return float(similarity)


print("Feature 1 function created: semantic_similarity")

In [ ]:
# TEST FEATURE 1: SEMANTIC SIMILARITY

test_job_text = """
We are looking for a Python developer with experience in
SQL and machine learning.
"""

test_resume_text = """
Software developer with experience in Python, SQL and
machine learning projects.
"""

test_semantic_score = calculate_semantic_similarity(
    test_job_text,
    test_resume_text
)

print("Semantic similarity:", test_semantic_score)
print("Type:", type(test_semantic_score))

In [ ]:
# FEATURE 2: KEYWORD OVERLAP

def calculate_keyword_overlap(job_text, resume_text):
    """
    Calculate the proportion of job-description words
    that also appear in the candidate resume.
    """

    resume_words = set(normalize_text(resume_text).split())
    job_words = set(normalize_text(job_text).split())

    if not job_words:
        return 0.0

    overlap = len(resume_words & job_words) / len(job_words)

    return float(overlap)


print("Feature 2 function created: keyword_overlap")

In [ ]:
# TEST FEATURE 2: KEYWORD OVERLAP

test_keyword_score = calculate_keyword_overlap(
    test_job_text,
    test_resume_text
)

print("Keyword overlap:", test_keyword_score)
print("Type:", type(test_keyword_score))

In [ ]:
# FEATURE 3: TF-IDF SIMILARITY

def calculate_tfidf_similarity(job_text, resume_text):
    """
    Calculate TF-IDF cosine similarity between the job description
    and candidate resume using the existing TF-IDF vectorizer.
    """

    job_vector = tfidf_vectorizer.transform([job_text])
    resume_vector = tfidf_vectorizer.transform([resume_text])

    similarity = cosine_similarity(
        job_vector,
        resume_vector
    )[0][0]

    return float(similarity)

print("Feature 3 function created: tfidf_similarity")

In [ ]:
# TEST FEATURE 3: TF-IDF SIMILARITY

test_tfidf_score = calculate_tfidf_similarity(
    test_job_text,
    test_resume_text
)

print("TF-IDF similarity:", test_tfidf_score)
print("Type:", type(test_tfidf_score))

In [ ]:
# FEATURE 4: REQUIRED SKILL COVERAGE

def calculate_required_skill_coverage(job_profile, candidate_profile):
    """
    Calculate the proportion of required job skills
    that are present in the candidate's skills.
    """

    required_skills = {
        skill.strip().lower()
        for skill in job_profile.required_skills
        if skill
    }

    candidate_skills = {
        skill.strip().lower()
        for skill in candidate_profile.skills
        if skill
    }

    if not required_skills:
        return 0.0

    matched_skills = required_skills & candidate_skills

    coverage = len(matched_skills) / len(required_skills)

    return float(coverage)


print("Feature 4 function created: required_skill_coverage")

In [ ]:
# TEST FEATURE 4: REQUIRED SKILL COVERAGE

test_required_skill_score = calculate_required_skill_coverage(
    test_job,
    test_candidate
)

print("Required skill coverage:", test_required_skill_score)
print("Type:", type(test_required_skill_score))

In [ ]:
# FEATURE 5: PREFERRED SKILL COVERAGE

def calculate_preferred_skill_coverage(job_profile, candidate_profile):
    """
    Calculate the proportion of preferred job skills
    that are present in the candidate's skills.
    """

    preferred_skills = {
        skill.strip().lower()
        for skill in job_profile.preferred_skills
        if skill
    }

    candidate_skills = {
        skill.strip().lower()
        for skill in candidate_profile.skills
        if skill
    }

    if not preferred_skills:
        return 0.0

    matched_skills = preferred_skills & candidate_skills

    coverage = len(matched_skills) / len(preferred_skills)

    return float(coverage)


print("Feature 5 function created: preferred_skill_coverage")

In [ ]:
# TEST FEATURE 5: PREFERRED SKILL COVERAGE

test_preferred_skill_score = calculate_preferred_skill_coverage(
    test_job,
    test_candidate
)

print("Preferred skill coverage:", test_preferred_skill_score)
print("Type:", type(test_preferred_skill_score))

In [ ]:
# FEATURE 6: EXPERIENCE MATCH

def calculate_experience_match(job_profile, candidate_profile):
    """
    Compare the candidate's experience with the job's
    minimum required experience.
    """

    required_years = float(job_profile.minimum_experience or 0.0)

    if required_years <= 0:
        return 1.0

    candidate_text = " ".join(
        str(item.get("text", ""))
        if isinstance(item, dict)
        else str(item)
        for item in candidate_profile.experience
    )

    matches = re.findall(
        r'(\d+(?:\.\d+)?)\s*\+?\s*years?',
        candidate_text.lower()
    )

    if not matches:
        candidate_years = 0.0
    else:
        candidate_years = max(float(x) for x in matches)

    return float(min(candidate_years / required_years, 1.0))


print("Feature 6 function created: experience_match")

In [ ]:
# TEST FEATURE 6: EXPERIENCE MATCH

test_experience_score = calculate_experience_match(
    test_job,
    test_candidate
)

print("Experience match:", test_experience_score)
print("Type:", type(test_experience_score))

In [ ]:
# FEATURE 7: EDUCATION MATCH

def calculate_education_match(job_profile, candidate_profile):
    """
    Calculate how well the candidate's education matches
    the education requirement of the job.
    """

    required_education = {
        str(term).strip().lower()
        for term in job_profile.education
        if term
    }

    candidate_education = {
        str(term).strip().lower()
        for term in candidate_profile.education
        if term
    }

    if not required_education:
        return 1.0

    matched = 0

    for required in required_education:
        if any(
            required in candidate
            or candidate in required
            for candidate in candidate_education
        ):
            matched += 1

    return float(matched / len(required_education))


print("Feature 7 function created: education_match")

In [ ]:
# FEATURE 8: PROJECT RELEVANCE

def calculate_project_relevance(job_profile, candidate_profile):
    """
    Calculate how relevant the candidate's projects are
    to the job responsibilities.
    """

    project_text = " ".join(
        str(item.get("text", ""))
        if isinstance(item, dict)
        else str(item)
        for item in candidate_profile.projects
    )

    responsibility_text = " ".join(
        str(item)
        for item in job_profile.responsibilities
    )

    if not project_text.strip() or not responsibility_text.strip():
        return 0.0

    project_words = set(normalize_text(project_text).split())
    responsibility_words = set(normalize_text(responsibility_text).split())

    if not responsibility_words:
        return 0.0

    overlap = len(project_words & responsibility_words)

    return float(overlap / len(responsibility_words))


print("Feature 8 function created: project_relevance")

In [ ]:
# FEATURE 9: CERTIFICATION RELEVANCE

def calculate_certification_relevance(job_profile, candidate_profile):
    """
    Calculate how relevant the candidate's certifications are
    to the job requirements and responsibilities.
    """

    certification_text = " ".join(
        str(item.get("text", ""))
        if isinstance(item, dict)
        else str(item)
        for item in candidate_profile.certifications
    )

    job_text = " ".join([
        *[str(skill) for skill in job_profile.required_skills],
        *[str(skill) for skill in job_profile.preferred_skills],
        *[str(item) for item in job_profile.responsibilities]
    ])

    if not certification_text.strip() or not job_text.strip():
        return 0.0

    certification_words = set(
        normalize_text(certification_text).split()
    )

    job_words = set(
        normalize_text(job_text).split()
    )

    if not job_words:
        return 0.0

    overlap = len(certification_words & job_words)

    return float(overlap / len(job_words))


print("Feature 9 function created: certification_relevance")

In [ ]:
# TEST FEATURES 7, 8, AND 9

test_education_score = calculate_education_match(
    test_job,
    test_candidate
)

test_project_score = calculate_project_relevance(
    test_job,
    test_candidate
)

test_certification_score = calculate_certification_relevance(
    test_job,
    test_candidate
)

print("Education match:", test_education_score)
print("Education type:", type(test_education_score))

print("\nProject relevance:", test_project_score)
print("Project type:", type(test_project_score))

print("\nCertification relevance:", test_certification_score)
print("Certification type:", type(test_certification_score))

In [ ]:
# FINAL 9-FEATURE VECTOR

def create_features_v2(job_text, resume_text, job_profile, candidate_profile):
    """
    Create the final 9-feature vector for the ML ranking model.
    The feature order must remain fixed.
    """

    semantic_similarity = calculate_semantic_similarity(
        job_text,
        resume_text
    )

    keyword_overlap = calculate_keyword_overlap(
        job_text,
        resume_text
    )

    tfidf_similarity = calculate_tfidf_similarity(
        job_text,
        resume_text
    )

    required_skill_coverage = calculate_required_skill_coverage(
        job_profile,
        candidate_profile
    )

    preferred_skill_coverage = calculate_preferred_skill_coverage(
        job_profile,
        candidate_profile
    )

    experience_match = calculate_experience_match(
        job_profile,
        candidate_profile
    )

    education_match = calculate_education_match(
        job_profile,
        candidate_profile
    )

    project_relevance = calculate_project_relevance(
        job_profile,
        candidate_profile
    )

    certification_relevance = calculate_certification_relevance(
        job_profile,
        candidate_profile
    )

    return [
        semantic_similarity,
        keyword_overlap,
        tfidf_similarity,
        required_skill_coverage,
        preferred_skill_coverage,
        experience_match,
        education_match,
        project_relevance,
        certification_relevance
    ]


print("Final 9-feature vector function created.")

In [ ]:
# TEST FINAL 9-FEATURE VECTOR

test_features = create_features_v2(
    test_job_text,
    test_resume_text,
    test_job,
    test_candidate
)

print("Feature vector:", test_features)
print("Number of features:", len(test_features))
print("All values are numeric:", all(isinstance(x, (int, float, np.number)) for x in test_features))

print("\nFeature order:")
feature_names = [
    "semantic_similarity",
    "keyword_overlap",
    "tfidf_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

for i, (name, value) in enumerate(zip(feature_names, test_features), start=1):
    print(f"{i}. {name}: {value}")

In [ ]:
# CHECK CURRENT PROJECT DATA

print("Available variables:")

for name in [
    "jobs",
    "candidates",
    "pairs",
    "ranking_dataset",
    "job_profile",
    "candidate_profile"
]:
    print(f"{name}: {name in globals()}")

In [ ]:
# INSPECT THE ACTUAL PROJECT DATA

print("pairs type:", type(pairs))
print("pairs shape:", pairs.shape)

print("\nColumns:")
print(pairs.columns.tolist())

print("\nFirst row:")
display(pairs.head(1))

In [ ]:
# UPLOAD MEMBER 3 NLP PACKAGE TO COLAB

from google.colab import files
import zipfile
import os
import sys

uploaded = files.upload()

zip_name = next(iter(uploaded))

extract_path = "/content/member3_nlp"

with zipfile.ZipFile(zip_name, "r") as zip_ref:
    zip_ref.extractall(extract_path)

if extract_path not in sys.path:
    sys.path.insert(0, extract_path)

print("Member 3 NLP package extracted successfully.")
print("Location:", extract_path)

In [ ]:
# CHECK EXTRACTED MEMBER 3 PACKAGE STRUCTURE

import os

for root, dirs, files in os.walk("/content/member3_nlp"):
    level = root.replace("/content/member3_nlp", "").count(os.sep)
    indent = "  " * level
    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}  {file}")

In [ ]:
# MAKE MEMBER 3 PACKAGE IMPORTABLE AS "nlp"

import sys
import os

parent_path = "/content"

if parent_path not in sys.path:
    sys.path.insert(0, parent_path)

os.rename(
    "/content/member3_nlp",
    "/content/nlp"
)

print("Member 3 package renamed to:", "/content/nlp")
print("nlp package exists:", os.path.isdir("/content/nlp"))
print("pipeline.py exists:", os.path.isfile("/content/nlp/pipeline.py"))

In [ ]:
# CHECK MEMBER 3 PACKAGE FILES

import os

required_files = [
    "/content/nlp/__init__.py",
    "/content/nlp/pipeline.py",
    "/content/nlp/extraction/__init__.py",
    "/content/nlp/extraction/candidate_extractor.py",
    "/content/nlp/extraction/job_extractor.py",
    "/content/nlp/parsing/__init__.py",
    "/content/nlp/quality_checks/__init__.py",
    "/content/nlp/ontology/__init__.py"
]

for path in required_files:
    print(path, "->", os.path.isfile(path))

In [ ]:
# RE-EXTRACT MEMBER 3 NLP PACKAGE CORRECTLY

import os
import zipfile
import shutil

zip_path = "/content/nlp.zip"
extract_path = "/content/nlp"

if os.path.exists(extract_path):
    shutil.rmtree(extract_path)

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    for member in zip_ref.infolist():
        corrected_name = member.filename.replace("\\", "/")
        target_path = os.path.join(extract_path, corrected_name)

        if member.is_dir():
            os.makedirs(target_path, exist_ok=True)
        else:
            os.makedirs(os.path.dirname(target_path), exist_ok=True)
            with zip_ref.open(member) as source, open(target_path, "wb") as target:
                target.write(source.read())

print("Member 3 NLP package re-extracted successfully.")
print("candidate_extractor.py:", os.path.isfile("/content/nlp/extraction/candidate_extractor.py"))
print("job_extractor.py:", os.path.isfile("/content/nlp/extraction/job_extractor.py"))
print("section_detector.py:", os.path.isfile("/content/nlp/parsing/section_detector.py"))
print("run_checks.py:", os.path.isfile("/content/nlp/quality_checks/run_checks.py"))

In [ ]:
!pip install rapidfuzz

In [ ]:
# IMPORT MEMBER 3 NLP PIPELINE

import sys

if "/content" not in sys.path:
    sys.path.insert(0, "/content")

from nlp.pipeline import process_job, process_candidate

print("Member 3 NLP pipeline imported successfully.")
print("process_job available:", "process_job" in globals())
print("process_candidate available:", "process_candidate" in globals())

In [ ]:
# TEST MEMBER 3 JOB PROFILE EXTRACTION

test_row = pairs.iloc[0]

actual_job_profile = process_job(
    test_row["job_id"],
    test_row["job_text"]
)

print("Job profile created successfully.")
print("Job ID:", actual_job_profile.job_id)
print("Required skills:", actual_job_profile.required_skills)
print("Preferred skills:", actual_job_profile.preferred_skills)
print("Minimum experience:", actual_job_profile.minimum_experience)
print("Education:", actual_job_profile.education)
print("Responsibilities:", actual_job_profile.responsibilities)

In [ ]:
# TEST MEMBER 3 CANDIDATE PROFILE EXTRACTION

test_row = pairs.iloc[0]

parsed_pages = [
    {
        "page": 1,
        "text": test_row["resume_text"]
    }
]

actual_candidate_profile = process_candidate(
    test_row["candidate_id"],
    parsed_pages
)

print("Candidate profile created successfully.")
print("Candidate ID:", actual_candidate_profile["profile"].candidate_id)
print("Skills:", actual_candidate_profile["profile"].skills)
print("Education:", actual_candidate_profile["profile"].education)
print("Experience:", actual_candidate_profile["profile"].experience)
print("Projects:", actual_candidate_profile["profile"].projects)
print("Certifications:", actual_candidate_profile["profile"].certifications)

In [ ]:
# INSPECT THE ACTUAL C001 RESUME TEXT

test_row = pairs.iloc[0]

print(test_row["resume_text"])

In [ ]:
# TEST MEMBER 3 EXTRACTION WITH STRUCTURED RESUME TEXT

structured_resume = """
NAME
C001

EDUCATION
Bachelor's degree in Computer Science

EXPERIENCE
Python Developer with 2 years of experience in machine learning and data analysis.

SKILLS
Python, SQL, Pandas, NumPy, scikit-learn, TensorFlow

PROJECTS
Machine learning classification and regression projects

CERTIFICATIONS
Python certification
"""

parsed_pages = [
    {
        "page": 1,
        "text": structured_resume
    }
]

test_profile = process_candidate(
    "TEST_C001",
    parsed_pages
)

profile = test_profile["profile"]

print("Skills:", profile.skills)
print("Education:", profile.education)
print("Experience:", profile.experience)
print("Projects:", profile.projects)
print("Certifications:", profile.certifications)

In [ ]:
# CONNECT MEMBER 3 PROFILES TO THE 9-FEATURE PIPELINE

test_job_profile = actual_job_profile
test_candidate_profile = profile

test_features = create_features_v2(
    test_row["job_text"],
    structured_resume,
    test_job_profile,
    test_candidate_profile
)

feature_names = [
    "semantic_similarity",
    "keyword_overlap",
    "tfidf_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

for name, value in zip(feature_names, test_features):
    print(f"{name}: {value}")

print("Number of features:", len(test_features))
print("All values numeric:", all(isinstance(x, (int, float, np.number)) for x in test_features))

In [ ]:
def calculate_project_relevance(job_profile, candidate_profile):
    project_text = " ".join(
        str(item.get("text", "")) if isinstance(item, dict) else str(item)
        for item in candidate_profile.projects
    )

    job_text = " ".join([
        *[str(skill) for skill in job_profile.required_skills],
        *[str(skill) for skill in job_profile.preferred_skills],
        *[str(item) for item in job_profile.responsibilities]
    ])

    if not project_text.strip() or not job_text.strip():
        return 0.0

    project_embedding = semantic_model.encode([project_text])
    job_embedding = semantic_model.encode([job_text])

    similarity = cosine_similarity(
        project_embedding,
        job_embedding
    )[0][0]

    return float(similarity)

In [ ]:
def calculate_certification_relevance(job_profile, candidate_profile):
    certification_text = " ".join(
        str(item.get("text", "")) if isinstance(item, dict) else str(item)
        for item in candidate_profile.certifications
    )

    job_text = " ".join([
        *[str(skill) for skill in job_profile.required_skills],
        *[str(skill) for skill in job_profile.preferred_skills],
        *[str(item) for item in job_profile.responsibilities]
    ])

    if not certification_text.strip() or not job_text.strip():
        return 0.0

    certification_embedding = semantic_model.encode([certification_text])
    job_embedding = semantic_model.encode([job_text])

    similarity = cosine_similarity(
        certification_embedding,
        job_embedding
    )[0][0]

    return float(similarity)

In [ ]:
# RE-TEST THE COMPLETE 9-FEATURE VECTOR

test_features = create_features_v2(
    test_row["job_text"],
    structured_resume,
    test_job_profile,
    test_candidate_profile
)

feature_names = [
    "semantic_similarity",
    "keyword_overlap",
    "tfidf_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

for name, value in zip(feature_names, test_features):
    print(f"{name}: {value}")

print("Number of features:", len(test_features))
print("All values numeric:", all(isinstance(x, (int, float, np.number)) for x in test_features))

In [ ]:
# CHECK CURRENT RANKING DATASET

print("Rows:", len(pairs))
print("Columns:", list(pairs.columns))
print()
print(pairs.head())

In [ ]:
# CHECK JOB AND CANDIDATE DISTRIBUTION

print("Number of jobs:", pairs["job_id"].nunique())
print("Number of candidates:", pairs["candidate_id"].nunique())

print("\nCandidates per job:")
print(pairs.groupby("job_id")["candidate_id"].count())

print("\nJob IDs:")
print(pairs["job_id"].unique())

print("\nCandidate IDs:")
print(pairs["candidate_id"].unique())

In [ ]:
# INSPECT THE 5 JOB DESCRIPTIONS

jobs_preview = (
    pairs[["job_id", "job_title", "job_text"]]
    .drop_duplicates("job_id")
    .sort_values("job_id")
    .reset_index(drop=True)
)

for _, row in jobs_preview.iterrows():
    print("=" * 80)
    print("Job ID:", row["job_id"])
    print("Job Title:", row["job_title"])
    print("Job Text:")
    print(row["job_text"])
    print()

In [ ]:
# INSPECT ALL 10 CANDIDATE RESUMES

candidates_preview = (
    pairs[["candidate_id", "resume_text"]]
    .drop_duplicates("candidate_id")
    .sort_values("candidate_id")
    .reset_index(drop=True)
)

for _, row in candidates_preview.iterrows():
    print("=" * 80)
    print("Candidate ID:", row["candidate_id"])
    print("Resume:")
    print(row["resume_text"])
    print()

In [ ]:
# CHECK WHETHER LABEL DATA ALREADY EXISTS

import os

for path in [
    "/content/drive/MyDrive/AI_Resume_Screening/data/raw/ranking_dataset.csv",
    "/content/drive/MyDrive/AI_Resume_Screening/data/raw/train.csv",
    "/content/drive/MyDrive/AI_Resume_Screening/data/raw/validation.csv",
    "/content/drive/MyDrive/AI_Resume_Screening/data/raw/test.csv"
]:
    print(path)
    print("Exists:", os.path.isfile(path))

    if os.path.isfile(path):
        temp = pd.read_csv(path)
        print("Columns:", list(temp.columns))
        print("Rows:", len(temp))
        print()

In [ ]:
# INSPECT EXISTING LABELED DATA

labeled_data = pd.read_csv(
    "/content/drive/MyDrive/AI_Resume_Screening/data/raw/ranking_dataset.csv"
)

print(labeled_data.to_string(index=False))

In [ ]:
label_map = {
    "J001": {
        "C001": 3,
        "C002": 0,
        "C003": 2,
        "C004": 2,
        "C005": 1,
        "C006": 0,
        "C007": 3,
        "C008": 1,
        "C009": 2,
        "C010": 1
    },
    "J002": {
        "C001": 2,
        "C002": 0,
        "C003": 3,
        "C004": 1,
        "C005": 2,
        "C006": 0,
        "C007": 2,
        "C008": 0,
        "C009": 3,
        "C010": 1
    },
    "J003": {
        "C001": 3,
        "C002": 1,
        "C003": 2,
        "C004": 3,
        "C005": 1,
        "C006": 0,
        "C007": 2,
        "C008": 1,
        "C009": 2,
        "C010": 2
    },
    "J004": {
        "C001": 1,
        "C002": 3,
        "C003": 0,
        "C004": 1,
        "C005": 0,
        "C006": 3,
        "C007": 1,
        "C008": 3,
        "C009": 0,
        "C010": 2
    },
    "J005": {
        "C001": 2,
        "C002": 0,
        "C003": 3,
        "C004": 1,
        "C005": 3,
        "C006": 0,
        "C007": 2,
        "C008": 0,
        "C009": 3,
        "C010": 1
    }
}

labeled_pairs = pairs.copy()

labeled_pairs["relevance_label"] = labeled_pairs.apply(
    lambda row: label_map[row["job_id"]][row["candidate_id"]],
    axis=1
)

print("Rows:", len(labeled_pairs))
print("Columns:", labeled_pairs.columns.tolist())
print()
print(labeled_pairs[
    ["job_id", "candidate_id", "relevance_label"]
].to_string(index=False))

In [ ]:
output_path = "/content/drive/MyDrive/AI_Resume_Screening/data/raw/ranking_dataset_labeled.csv"

labeled_pairs.to_csv(output_path, index=False)

print("Saved successfully:")
print(output_path)

print("\nShape:", labeled_pairs.shape)
print("Label counts:")
print(labeled_pairs["relevance_label"].value_counts().sort_index())

In [ ]:
feature_rows = []

for _, row in labeled_pairs.iterrows():
    job_profile = process_job(
        row["job_id"],
        row["job_text"]
    )

    parsed_pages = [
        {
            "page": 1,
            "text": row["resume_text"]
        }
    ]

    candidate_result = process_candidate(
        row["candidate_id"],
        parsed_pages
    )

    candidate_profile = candidate_result["profile"]

    features = create_features_v2(
        row["job_text"],
        row["resume_text"],
        job_profile,
        candidate_profile
    )

    feature_rows.append(features)

feature_columns = [
    "semantic_similarity",
    "keyword_overlap",
    "tfidf_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

features_df = pd.DataFrame(
    feature_rows,
    columns=feature_columns
)

ml_dataset = pd.concat(
    [
        labeled_pairs[
            ["job_id", "job_title", "candidate_id", "relevance_label"]
        ].reset_index(drop=True),
        features_df.reset_index(drop=True)
    ],
    axis=1
)

print("ML dataset shape:", ml_dataset.shape)
print()
print(ml_dataset.head(10).to_string(index=False))

In [ ]:
profile_stats = []

for _, row in labeled_pairs.iterrows():
    parsed_pages = [
        {
            "page": 1,
            "text": row["resume_text"]
        }
    ]

    candidate_result = process_candidate(
        row["candidate_id"],
        parsed_pages
    )

    profile = candidate_result["profile"]

    profile_stats.append({
        "candidate_id": row["candidate_id"],
        "education_items": len(profile.education),
        "experience_items": len(profile.experience),
        "project_items": len(profile.projects),
        "certification_items": len(profile.certifications),
        "skill_items": len(profile.skills)
    })

profile_stats_df = pd.DataFrame(profile_stats)

print(profile_stats_df.to_string(index=False))

print("\nTotal non-empty profiles:")
print("Education:", (profile_stats_df["education_items"] > 0).sum())
print("Experience:", (profile_stats_df["experience_items"] > 0).sum())
print("Projects:", (profile_stats_df["project_items"] > 0).sum())
print("Certifications:", (profile_stats_df["certification_items"] > 0).sum())
print("Skills:", (profile_stats_df["skill_items"] > 0).sum())

In [ ]:
structured_resumes = {
    "C001": """Experience:
Python Developer with 2 years of experience in machine learning and data analysis.

Skills:
Python, TensorFlow, SQL, Pandas, NumPy, Scikit-learn, Machine Learning, Data Analysis.

Education:
Bachelor's degree in Computer Science.

Projects:
Machine learning classification and regression projects.

Certifications:
Python certification.""",

    "C002": """Experience:
Full Stack Developer with 3 years of experience building web applications.

Skills:
JavaScript, React, Node.js, HTML, CSS, SQL, REST API.

Education:
Bachelor's degree in Computer Science.

Projects:
Full stack web application development projects.

Certifications:
Web Development certification.""",

    "C003": """Experience:
Data Scientist with 2 years of experience in Python, statistics, machine learning, and data analysis.

Skills:
Python, Statistics, Machine Learning, SQL, Pandas, NumPy, Data Analysis, Data Visualization.

Education:
Bachelor's degree in Statistics.

Projects:
Predictive modeling and data visualization projects.

Certifications:
Data Science certification.""",

    "C004": """Experience:
Python Backend Developer with 2 years of experience developing backend applications.

Skills:
Python, Flask, Django, SQL, REST API.

Education:
Bachelor's degree in Computer Science.

Projects:
Backend application and database integration projects.

Certifications:
Python certification.""",

    "C005": """Experience:
Data Analyst with 2 years of experience in data analysis and statistical reporting.

Skills:
SQL, Python, Excel, Statistics, Data Visualization, Pandas, Power BI, Tableau.

Education:
Bachelor's degree in Business Analytics.

Projects:
Business data analysis and visualization projects.

Certifications:
Data Analytics certification.""",

    "C006": """Experience:
Frontend Developer with 2 years of experience developing responsive web interfaces.

Skills:
HTML, CSS, JavaScript, React.

Education:
Bachelor's degree in Computer Science.

Projects:
Responsive web design and user interface projects.

Certifications:
Frontend Development certification.""",

    "C007": """Experience:
Machine Learning Engineer with 3 years of experience in machine learning and deep learning.

Skills:
Python, Machine Learning, Deep Learning, SQL, TensorFlow, Scikit-learn.

Education:
Bachelor's degree in Computer Engineering.

Projects:
Predictive modeling and machine learning deployment projects.

Certifications:
Machine Learning certification.""",

    "C008": """Experience:
Software Developer with 3 years of experience developing full stack web applications.

Skills:
JavaScript, React, Node.js, HTML, CSS, SQL, REST API.

Education:
Bachelor's degree in Information Technology.

Projects:
Full stack web application development projects.

Certifications:
Web Development certification.""",

    "C009": """Experience:
Data Scientist with 3 years of experience in statistics, Python, SQL, and machine learning.

Skills:
Statistics, Python, SQL, Machine Learning, Data Analysis, Data Visualization, Pandas, NumPy, Scikit-learn.

Education:
Master's degree in Statistics.

Projects:
Predictive modeling, data analysis, and data visualization projects.

Certifications:
Data Science certification.""",

    "C010": """Experience:
Software Developer with 2 years of experience developing software applications and database systems.

Skills:
Java, Python, SQL, Web Development.

Education:
Bachelor's degree in Computer Science.

Projects:
Software application and database development projects.

Certifications:
Software Development certification."""
}

print("Number of structured resumes:", len(structured_resumes))
print("Candidate IDs:", list(structured_resumes.keys()))

In [ ]:
profile_check = []

for candidate_id, resume_text in structured_resumes.items():
    parsed_pages = [
        {
            "page": 1,
            "text": resume_text
        }
    ]

    result = process_candidate(
        candidate_id,
        parsed_pages
    )

    profile = result["profile"]

    profile_check.append({
        "candidate_id": candidate_id,
        "skills": len(profile.skills),
        "education": len(profile.education),
        "experience": len(profile.experience),
        "projects": len(profile.projects),
        "certifications": len(profile.certifications)
    })

profile_check_df = pd.DataFrame(profile_check)

print(profile_check_df.to_string(index=False))

In [ ]:
from nlp.parsing.section_detector import detect_sections

test_resume = structured_resumes["C001"]

parsed_pages = [
    {
        "page": 1,
        "text": test_resume
    }
]

sections = detect_sections(parsed_pages)

print("Detected sections:")
print(sections)

In [ ]:
from nlp.parsing.section_detector import SECTION_PATTERNS

print(SECTION_PATTERNS)

In [ ]:
structured_resumes = {
    "C001": """Experience
Python Developer with 2 years of experience in machine learning and data analysis.

Skills
Python, TensorFlow, SQL, Pandas, NumPy, Scikit-learn, Machine Learning, Data Analysis.

Education
Bachelor's degree in Computer Science.

Projects
Machine learning classification and regression projects.

Certifications
Python certification.""",

    "C002": """Experience
Full Stack Developer with 3 years of experience building web applications.

Skills
JavaScript, React, Node.js, HTML, CSS, SQL, REST API, Frontend, Backend.

Education
Bachelor's degree in Computer Science.

Projects
Full stack web application development projects.

Certifications
Web development certification.""",

    "C003": """Experience
Data Scientist with 2 years of experience in data science and predictive modeling.

Skills
Python, Statistics, Machine Learning, SQL, Pandas, NumPy, Data Analysis, Visualization.

Education
Bachelor's degree in Statistics.

Projects
Predictive modeling and data analysis projects.

Certifications
Data Science certification.""",

    "C004": """Experience
Python Backend Developer with 2 years of experience developing backend applications.

Skills
Python, Flask, Django, SQL, REST API, Backend, Database Integration.

Education
Bachelor's degree in Computer Science.

Projects
Python backend and REST API development projects.

Certifications
Python certification.""",

    "C005": """Experience
Data Analyst with 2 years of experience in data analysis and reporting.

Skills
SQL, Python, Excel, Statistics, Visualization, Pandas, Power BI, Tableau.

Education
Bachelor's degree in Business Analytics.

Projects
Data analysis and business intelligence projects.

Certifications
Data Analytics certification.""",

    "C006": """Experience
Frontend Developer with 2 years of experience developing responsive web interfaces.

Skills
HTML, CSS, JavaScript, React, Frontend, Responsive Web Design, UI Development.

Education
Bachelor's degree in Computer Science.

Projects
Responsive web interface and frontend development projects.

Certifications
Frontend development certification.""",

    "C007": """Experience
Machine Learning Engineer with 3 years of experience in machine learning and deep learning.

Skills
Python, Machine Learning, Deep Learning, SQL, TensorFlow, Scikit-learn, Predictive Modeling, Deployment.

Education
Bachelor's degree in Computer Engineering.

Projects
Machine learning, deep learning, predictive modeling, and model deployment projects.

Certifications
Machine Learning certification.""",

    "C008": """Experience
Software Developer with 3 years of experience developing full stack web applications.

Skills
JavaScript, React, Node.js, HTML, CSS, SQL, REST API, Full Stack, Web Development.

Education
Bachelor's degree in Information Technology.

Projects
Full stack web application development projects.

Certifications
Web development certification.""",

    "C009": """Experience
Data Scientist with 3 years of experience in statistics, machine learning, and data analysis.

Skills
Statistics, Python, SQL, Machine Learning, Data Analysis, Visualization, Predictive Modeling, Pandas, NumPy, Scikit-learn.

Education
Master's degree in Statistics.

Projects
Predictive modeling, machine learning, and data visualization projects.

Certifications
Data Science certification.""",

    "C010": """Experience
Software Developer with 2 years of experience developing software applications and database systems.

Skills
Java, Python, SQL, Web Development, Software Development, Database Systems.

Education
Bachelor's degree in Computer Science.

Projects
Software application and database development projects.

Certifications
Software development certification."""
}

print("Number of structured resumes:", len(structured_resumes))
print("Candidate IDs:", list(structured_resumes.keys()))

In [ ]:
import inspect

print(inspect.signature(process_candidate))

In [ ]:
parsed_profiles = {}
for candidate_id, resume_text in structured_resumes.items():
    parsed_pages = [
        {
            "page": 1,
            "text": resume_text
        }
    ]
    result = process_candidate(candidate_id, parsed_pages)
    parsed_profiles[candidate_id] = result

first_profile = parsed_profiles["C001"]

print("Type:", type(first_profile))
print("\nKeys:")
print(first_profile.keys())

print("\nC001 profile:")
print(first_profile)

In [ ]:
for candidate_id, result in parsed_profiles.items():
    profile = result["profile"]
    quality = result["quality"]

    print(
        candidate_id,
        "| skills:", len(profile.skills),
        "| education:", len(profile.education),
        "| experience:", len(profile.experience),
        "| projects:", len(profile.projects),
        "| certifications:", len(profile.certifications),
        "| quality:", quality["quality_status"]
    )

In [ ]:
import inspect

print(inspect.signature(process_job))

In [ ]:
print("Job profile type:", type(job_result))

print("\nJob profile:")
print(job_result)

print("\nRequired skills:")
print(job_result.required_skills)

print("\nPreferred skills:")
print(job_result.preferred_skills)

print("\nMinimum experience:")
print(job_result.minimum_experience)

print("\nEducation:")
print(job_result.education)

In [ ]:
parsed_jobs = {}

for job_id in pairs["job_id"].unique():
    job_text = pairs[pairs["job_id"] == job_id]["job_text"].iloc[0]
    parsed_jobs[job_id] = process_job(job_id, job_text)

print("Job extraction results:")

for job_id, profile in parsed_jobs.items():
    print(
        job_id,
        "| required skills:", len(profile.required_skills),
        "| preferred skills:", len(profile.preferred_skills),
        "| minimum experience:", profile.minimum_experience,
        "| education:", len(profile.education),
        "| responsibilities:", len(profile.responsibilities)
    )

In [ ]:
feature_columns = [
    "semantic_similarity",
    "keyword_overlap",
    "tfidf_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

feature_rows = []

for _, row in pairs.iterrows():
    job_id = row["job_id"]
    candidate_id = row["candidate_id"]

    job_text = row["job_text"]
    resume_text = row["resume_text"]

    job_profile = parsed_jobs[job_id]
    candidate_profile = parsed_profiles[candidate_id]["profile"]

    features = create_features_v2(
        job_text,
        resume_text,
        job_profile,
        candidate_profile
    )

    feature_rows.append(
        [job_id, candidate_id] + features
    )

feature_df = pd.DataFrame(
    feature_rows,
    columns=["job_id", "candidate_id"] + feature_columns
)

print("Feature matrix shape:", feature_df.shape)
print("\nColumns:")
print(feature_df.columns.tolist())

print("\nFirst 10 rows:")
display(feature_df.head(10))

In [ ]:
print("Feature statistics:")
display(feature_df[feature_columns].describe().T)

print("\nUnique values per feature:")
for column in feature_columns:
    print(
        f"{column}:",
        feature_df[column].nunique(),
        "unique values"
    )

In [ ]:
import inspect
from nlp.extraction.job_extractor import extract_job_skills_by_type

print(inspect.getsource(extract_job_skills_by_type))

In [ ]:
from nlp.extraction.job_extractor import detect_job_section_heading
import inspect

print(inspect.getsource(detect_job_section_heading))

In [ ]:
from nlp.extraction.job_extractor import JOB_SECTION_PATTERNS

print(JOB_SECTION_PATTERNS)

In [ ]:
test_job = """ML Engineer

Requirements
Python, Machine Learning, Deep Learning, SQL, Data Analysis

Preferred Skills
Pandas, NumPy, Scikit-learn, TensorFlow

Education
Bachelor's degree in Computer Science, Computer Engineering, Mathematics
"""

test_profile = process_job("J001_TEST", test_job)

print("Required skills:", test_profile.required_skills)
print("Preferred skills:", test_profile.preferred_skills)
print("Minimum experience:", test_profile.minimum_experience)
print("Education:", test_profile.education)

In [ ]:
import inspect
from nlp.extraction.job_extractor import extract_minimum_experience

print(inspect.getsource(extract_minimum_experience))

In [ ]:
test_job_experience = """ML Engineer

Requirements
Python, Machine Learning, Deep Learning, SQL, Data Analysis

Preferred Skills
Pandas, NumPy, Scikit-learn, TensorFlow

Minimum 2 years of experience

Education
Bachelor's degree in Computer Science, Computer Engineering, Mathematics
"""

test_profile = process_job("J001_TEST", test_job_experience)

print("Required skills:", test_profile.required_skills)
print("Preferred skills:", test_profile.preferred_skills)
print("Minimum experience:", test_profile.minimum_experience)
print("Education:", test_profile.education)

In [ ]:
pairs_structured = pairs.copy()

print(pairs_structured.shape)
print(pairs_structured[["job_id", "job_title"]].drop_duplicates().to_string(index=False))

In [ ]:
structured_job_texts = {
    "J001": """Machine Learning Engineer

Requirements
Python, Machine Learning, Deep Learning, SQL, Data Analysis

Preferred Skills
Pandas, NumPy, Scikit-learn, TensorFlow

Minimum 2 years of experience

Education
Bachelor's degree in Computer Science, Computer Engineering, Mathematics, or related field""",

    "J002": """Data Scientist

Requirements
Python, Statistics, SQL, Machine Learning, Data Analysis, Visualization

Preferred Skills
Pandas, NumPy, Scikit-learn

Minimum 2 years of experience

Education
Bachelor's degree in Statistics, Computer Science, Mathematics, or related field""",

    "J003": """Python Developer

Requirements
Python, SQL, Backend, REST API

Preferred Skills
Django, Flask

Minimum 2 years of experience

Education
Bachelor's degree in Computer Science, Computer Engineering, or related field""",

    "J004": """Full Stack Developer

Requirements
JavaScript, React, Node.js, HTML, CSS, SQL, REST API

Preferred Skills
Full Stack, Web Development

Minimum 3 years of experience

Education
Bachelor's degree in Computer Science, Information Technology, or related field""",

    "J005": """Data Analyst

Requirements
SQL, Python, Excel, Statistics, Visualization

Preferred Skills
Pandas, Power BI, Tableau

Minimum 2 years of experience

Education
Bachelor's degree in Statistics, Computer Science, Business Analytics, or related field"""
}

pairs_structured["job_text"] = pairs_structured["job_id"].map(structured_job_texts)

print(pairs_structured[["job_id", "job_title", "job_text"]].drop_duplicates().to_string(index=False))

In [ ]:
parsed_jobs_structured = {}

for job_id, job_text in structured_job_texts.items():
    profile = process_job(job_id, job_text)
    parsed_jobs_structured[job_id] = profile

    print(f"\n{job_id}")
    print("Required skills:", profile.required_skills)
    print("Preferred skills:", profile.preferred_skills)
    print("Minimum experience:", profile.minimum_experience)
    print("Education:", profile.education)

In [ ]:
# Rebuild candidate profiles from the structured resumes
parsed_profiles_structured = {}

for candidate_id, resume_text in structured_resumes.items():
    parsed_pages = [
        {
            "page": 1,
            "text": resume_text
        }
    ]

    result = process_candidate(candidate_id, parsed_pages)
    parsed_profiles_structured[candidate_id] = result["profile"]

# Build the 9-feature matrix
feature_rows = []

for _, row in pairs_structured.iterrows():
    job_id = row["job_id"]
    candidate_id = row["candidate_id"]

    job_profile = parsed_jobs_structured[job_id]
    candidate_profile = parsed_profiles_structured[candidate_id]

    features = create_features_v2(
        row["job_text"],
        row["resume_text"],
        job_profile,
        candidate_profile
    )

    feature_rows.append({
        "job_id": job_id,
        "candidate_id": candidate_id,
        "semantic_similarity": features[0],
        "keyword_overlap": features[1],
        "tfidf_similarity": features[2],
        "required_skill_coverage": features[3],
        "preferred_skill_coverage": features[4],
        "experience_match": features[5],
        "education_match": features[6],
        "project_relevance": features[7],
        "certification_relevance": features[8]
    })

feature_df_v2 = pd.DataFrame(feature_rows)

print("Shape:", feature_df_v2.shape)
print("\nColumns:")
print(feature_df_v2.columns.tolist())

print("\nFeature statistics:")
print(feature_df_v2.drop(columns=["job_id", "candidate_id"]).describe().T)

In [ ]:
print(labeled_pairs.columns.tolist())
print(labeled_pairs.head().to_string(index=False))

In [ ]:
label_lookup = labeled_pairs[
    ["job_id", "candidate_id", "relevance_label"]
].copy()

feature_df_labeled_v2 = feature_df_v2.merge(
    label_lookup,
    on=["job_id", "candidate_id"],
    how="left"
)

print("Shape:", feature_df_labeled_v2.shape)

print("\nMissing labels:", feature_df_labeled_v2["relevance_label"].isna().sum())

print("\nLabel counts:")
print(
    feature_df_labeled_v2["relevance_label"]
    .value_counts()
    .sort_index()
)

print("\nSample:")
print(
    feature_df_labeled_v2.head(10).to_string(index=False)
)

In [ ]:
feature_columns = [
    "semantic_similarity",
    "keyword_overlap",
    "tfidf_similarity",
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

label_summary = (
    feature_df_labeled_v2
    .groupby("relevance_label")[feature_columns]
    .mean()
    .round(3)
)

print(label_summary)

In [ ]:
#prepare xgboost training data
from sklearn.model_selection import train_test_split

X = feature_df_labeled_v2[feature_columns].copy()
y = feature_df_labeled_v2["relevance_label"].copy()
groups = feature_df_labeled_v2["job_id"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Groups:")
print(groups.value_counts().sort_index())

In [ ]:
from sklearn.model_selection import train_test_split

job_ids = feature_df_labeled_v2["job_id"].unique()

train_jobs, test_jobs = train_test_split(
    job_ids,
    test_size=0.4,
    random_state=42
)

train_df = feature_df_labeled_v2[
    feature_df_labeled_v2["job_id"].isin(train_jobs)
].copy()

test_df = feature_df_labeled_v2[
    feature_df_labeled_v2["job_id"].isin(test_jobs)
].copy()

print("Training jobs:", sorted(train_jobs))
print("Test jobs:", sorted(test_jobs))

print("\nTraining shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\nTraining group sizes:")
print(train_df["job_id"].value_counts().sort_index())

print("\nTest group sizes:")
print(test_df["job_id"].value_counts().sort_index())

In [ ]:
#train the 9 features xgboost ranker
from xgboost import XGBRanker

X_train = train_df[feature_columns]
y_train = train_df["relevance_label"]

X_test = test_df[feature_columns]
y_test = test_df["relevance_label"]

train_group = train_df.groupby("job_id", sort=False).size().tolist()
test_group = test_df.groupby("job_id", sort=False).size().tolist()

print("Training group sizes:", train_group)
print("Test group sizes:", test_group)

ranker_v2 = XGBRanker(
    objective="rank:ndcg",
    eval_metric="ndcg@5",
    learning_rate=0.05,
    max_depth=4,
    n_estimators=100,
    random_state=42,
    enable_categorical=False
)

ranker_v2.fit(
    X_train,
    y_train,
    group=train_group
)

print("\nXGBoost Ranker trained successfully.")
print("Number of features:", X_train.shape[1])
print("Features:", X_train.columns.tolist())

In [ ]:
#evaluate the trained model
from sklearn.metrics import ndcg_score

# Predict scores for unseen test jobs
test_df = test_df.copy()
test_df["xgb_score"] = ranker_v2.predict(X_test)

# Calculate NDCG@5 separately for each test job
ndcg_scores = {}

for job_id, group in test_df.groupby("job_id"):
    true_relevance = group["relevance_label"].to_numpy().reshape(1, -1)
    predicted_scores = group["xgb_score"].to_numpy().reshape(1, -1)

    ndcg = ndcg_score(
        true_relevance,
        predicted_scores,
        k=5
    )

    ndcg_scores[job_id] = ndcg

overall_ndcg = sum(ndcg_scores.values()) / len(ndcg_scores)

# Calculate MRR
reciprocal_ranks = []

for job_id, group in test_df.groupby("job_id"):
    ranked_group = group.sort_values("xgb_score", ascending=False)

    relevant_positions = (
        ranked_group["relevance_label"].to_numpy() > 0
    )

    if relevant_positions.any():
        first_relevant_rank = relevant_positions.argmax() + 1
        reciprocal_ranks.append(1 / first_relevant_rank)
    else:
        reciprocal_ranks.append(0)

mrr = sum(reciprocal_ranks) / len(reciprocal_ranks)

print("NDCG@5 by job:")
for job_id, score in ndcg_scores.items():
    print(f"{job_id}: {score:.4f}")

print(f"\nOverall NDCG@5: {overall_ndcg:.4f}")
print(f"MRR: {mrr:.4f}")

print("\nPredicted ranking:")
print(
    test_df[
        ["job_id", "candidate_id", "relevance_label", "xgb_score"]
    ]
    .sort_values(["job_id", "xgb_score"], ascending=[True, False])
    .to_string(index=False)
)

In [ ]:
#On our current prototype test split consisting of two unseen jobs, the nine-feature XGBoost learning-to-rank model achieved an overall NDCG@5 of 0.9427 and an MRR of 1.0

In [ ]:
print(tfidf_vectorizer)

In [ ]:
print("Vocabulary size:", len(tfidf_vectorizer.vocabulary_))

In [ ]:
print(tfidf_vectorizer.get_params())

In [ ]:
print("Training jobs:", sorted(train_jobs))
print("Test jobs:", sorted(test_jobs))
print("Training rows:", len(X_train))
print("Test rows:", len(X_test))

In [ ]:
test_df = feature_df_labeled_v2[
    feature_df_labeled_v2["job_id"].isin(test_jobs)
].copy()

print(test_df.shape)
print(test_df.groupby("job_id")["candidate_id"].count())
print(test_df[["job_id", "candidate_id", "relevance_label"]].to_string(index=False))

In [ ]:
test_df = feature_df_labeled_v2[
    feature_df_labeled_v2["job_id"].isin(test_jobs)
].copy()

test_df = test_df.merge(
    pairs_structured[[
        "job_id",
        "candidate_id",
        "job_text",
        "resume_text"
    ]],
    on=["job_id", "candidate_id"],
    how="left"
)

print(test_df.shape)
print(test_df[[
    "job_id",
    "candidate_id",
    "job_text",
    "resume_text",
    "relevance_label"
]].head(2).to_string(index=False))

In [ ]:
def keyword_baseline_score(job_text, resume_text):
    job_words = set(normalize_text(job_text).split())
    resume_words = set(normalize_text(resume_text).split())

    if not job_words:
        return 0.0

    return len(job_words & resume_words) / len(job_words)


keyword_results = []

for _, row in test_df.iterrows():
    score = keyword_baseline_score(
        row["job_text"],
        row["resume_text"]
    )

    keyword_results.append({
        "job_id": row["job_id"],
        "candidate_id": row["candidate_id"],
        "score": score,
        "relevance_label": row["relevance_label"]
    })

keyword_results_df = pd.DataFrame(keyword_results)

print(keyword_results_df.head(10).to_string(index=False))

In [ ]:
from sklearn.metrics import ndcg_score


def calculate_ranking_metrics(results_df):
    ndcg_scores = []
    reciprocal_ranks = []

    for job_id, group in results_df.groupby("job_id"):
        y_true = group["relevance_label"].to_numpy()
        y_score = group["score"].to_numpy()

        ndcg = ndcg_score(
            [y_true],
            [y_score],
            k=5
        )
        ndcg_scores.append(ndcg)

        ranked_group = group.sort_values(
            "score",
            ascending=False
        ).reset_index(drop=True)

        relevant_positions = ranked_group.index[
            ranked_group["relevance_label"] > 0
        ]

        if len(relevant_positions) > 0:
            reciprocal_ranks.append(
                1.0 / (relevant_positions[0] + 1)
            )

    return {
        "NDCG@5": sum(ndcg_scores) / len(ndcg_scores),
        "MRR": sum(reciprocal_ranks) / len(reciprocal_ranks)
    }


keyword_metrics = calculate_ranking_metrics(keyword_results_df)

print("Keyword Baseline")
print(f"NDCG@5: {keyword_metrics['NDCG@5']:.4f}")
print(f"MRR:     {keyword_metrics['MRR']:.4f}")

In [ ]:
tfidf_results = []

for _, row in test_df.iterrows():
    score = calculate_tfidf_similarity(
        row["job_text"],
        row["resume_text"]
    )

    tfidf_results.append({
        "job_id": row["job_id"],
        "candidate_id": row["candidate_id"],
        "score": score,
        "relevance_label": row["relevance_label"]
    })

tfidf_results_df = pd.DataFrame(tfidf_results)

print(tfidf_results_df.head(10).to_string(index=False))

In [ ]:
tfidf_metrics = calculate_ranking_metrics(tfidf_results_df)

print("TF-IDF Baseline")
print(f"NDCG@5: {tfidf_metrics['NDCG@5']:.4f}")
print(f"MRR:     {tfidf_metrics['MRR']:.4f}")

In [ ]:
semantic_results = []

for _, row in test_df.iterrows():
    score = calculate_semantic_similarity(
        row["job_text"],
        row["resume_text"]
    )

    semantic_results.append({
        "job_id": row["job_id"],
        "candidate_id": row["candidate_id"],
        "score": score,
        "relevance_label": row["relevance_label"]
    })

semantic_results_df = pd.DataFrame(semantic_results)

print(semantic_results_df.head(10).to_string(index=False))

In [ ]:
semantic_metrics = calculate_ranking_metrics(semantic_results_df)

print("Semantic Baseline")
print(f"NDCG@5: {semantic_metrics['NDCG@5']:.4f}")
print(f"MRR:     {semantic_metrics['MRR']:.4f}")

In [ ]:
structured_feature_columns = [
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

structured_results_df = test_df[
    ["job_id", "candidate_id", "relevance_label"] +
    structured_feature_columns
].copy()

structured_results_df["score"] = (
    structured_results_df[structured_feature_columns].mean(axis=1)
)

structured_results_df = structured_results_df[
    ["job_id", "candidate_id", "score", "relevance_label"]
]

print(structured_results_df.head(10).to_string(index=False))

In [ ]:
structured_metrics = calculate_ranking_metrics(structured_results_df)

print("Structured Feature Baseline")
print(f"NDCG@5: {structured_metrics['NDCG@5']:.4f}")
print(f"MRR:     {structured_metrics['MRR']:.4f}")

In [ ]:
xgb_results = []

for idx, row in test_df.iterrows():
    features = row[feature_columns].to_numpy(dtype=float).reshape(1, -1)

    score = ranker_v2.predict(features)[0]

    xgb_results.append({
        "job_id": row["job_id"],
        "candidate_id": row["candidate_id"],
        "score": float(score),
        "relevance_label": row["relevance_label"]
    })

xgb_results_df = pd.DataFrame(xgb_results)

print(xgb_results_df.head(10).to_string(index=False))

In [ ]:
xgb_metrics = calculate_ranking_metrics(xgb_results_df)

print("XGBoost 9-Feature Ranker")
print(f"NDCG@5: {xgb_metrics['NDCG@5']:.4f}")
print(f"MRR:     {xgb_metrics['MRR']:.4f}")

In [ ]:
for job_id, group in xgb_results_df.groupby("job_id"):
    print(f"\n{job_id}")

    display(
        group.sort_values("score", ascending=False)[
            ["candidate_id", "score", "relevance_label"]
        ].reset_index(drop=True)
    )

In [ ]:
train_df = feature_df_labeled_v2[
    feature_df_labeled_v2["job_id"].isin(train_jobs)
].copy()

print(train_df.groupby("job_id")["candidate_id"].count())
print("\nLabel distribution:")
print(train_df.groupby(["job_id", "relevance_label"]).size())

In [ ]:
from xgboost import XGBRanker
from sklearn.metrics import ndcg_score
import numpy as np
import pandas as pd

validation_jobs = train_jobs.copy()

print("LOJO validation jobs:", sorted(validation_jobs))
print("Final test jobs:", sorted(test_jobs))

In [ ]:
#leave one job out validation
lojo_results = []

for validation_job in validation_jobs:

    train_fold = train_df[
        train_df["job_id"] != validation_job
    ].copy()

    validation_fold = train_df[
        train_df["job_id"] == validation_job
    ].copy()

    X_fold_train = train_fold[feature_columns]
    y_fold_train = train_fold["relevance_label"]

    X_fold_val = validation_fold[feature_columns]
    y_fold_val = validation_fold["relevance_label"]

    train_groups = (
        train_fold.groupby("job_id")
        .size()
        .to_numpy()
    )

    model = XGBRanker(
        objective="rank:ndcg",
        eval_metric="ndcg@5",
        learning_rate=0.05,
        max_depth=4,
        n_estimators=100,
        random_state=42,
        enable_categorical=False
    )

    model.fit(
        X_fold_train,
        y_fold_train,
        group=train_groups
    )

    validation_scores = model.predict(X_fold_val)

    ndcg = ndcg_score(
        [y_fold_val.to_numpy()],
        [validation_scores],
        k=5
    )

    validation_result = pd.DataFrame({
        "candidate_id": validation_fold["candidate_id"].values,
        "score": validation_scores,
        "relevance_label": validation_fold["relevance_label"].values
    })

    validation_result = validation_result.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    relevant_positions = validation_result.index[
        validation_result["relevance_label"] > 0
    ]

    mrr = (
        1.0 / (relevant_positions[0] + 1)
        if len(relevant_positions) > 0
        else 0.0
    )

    lojo_results.append({
        "validation_job": validation_job,
        "NDCG@5": ndcg,
        "MRR": mrr
    })

lojo_results_df = pd.DataFrame(lojo_results)

print(lojo_results_df.to_string(index=False))

print("\nMean LOJO NDCG@5:",
      f"{lojo_results_df['NDCG@5'].mean():.4f}")

print("Mean LOJO MRR:",
      f"{lojo_results_df['MRR'].mean():.4f}")

In [ ]:
train_df = feature_df_labeled_v2[
    feature_df_labeled_v2["job_id"].isin(train_jobs)
].copy()

train_df = train_df.merge(
    pairs_structured[
        ["job_id", "candidate_id", "job_text", "resume_text"]
    ],
    on=["job_id", "candidate_id"],
    how="left"
)

print(train_df.shape)
print(train_df[[
    "job_id",
    "candidate_id",
    "job_text",
    "resume_text",
    "relevance_label"
]].head(2).to_string(index=False))

In [ ]:
#same as 296
keyword_lojo_results = []

for validation_job in validation_jobs:
    validation_fold = train_df[
        train_df["job_id"] == validation_job
    ].copy()

    scores = []

    for _, row in validation_fold.iterrows():
        score = keyword_baseline_score(
            row["job_text"],
            row["resume_text"]
        )
        scores.append(score)

    y_true = validation_fold["relevance_label"].to_numpy()

    ndcg = ndcg_score(
        [y_true],
        [np.array(scores)],
        k=5
    )

    ranking = validation_fold[
        ["candidate_id", "relevance_label"]
    ].copy()

    ranking["score"] = scores

    ranking = ranking.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    relevant_positions = ranking.index[
        ranking["relevance_label"] > 0
    ]

    mrr = (
        1.0 / (relevant_positions[0] + 1)
        if len(relevant_positions) > 0
        else 0.0
    )

    keyword_lojo_results.append({
        "validation_job": validation_job,
        "NDCG@5": ndcg,
        "MRR": mrr
    })

keyword_lojo_df = pd.DataFrame(keyword_lojo_results)

print(keyword_lojo_df.to_string(index=False))
print("\nMean LOJO NDCG@5:", f"{keyword_lojo_df['NDCG@5'].mean():.4f}")
print("Mean LOJO MRR:", f"{keyword_lojo_df['MRR'].mean():.4f}")

In [ ]:
tfidf_lojo_results = []

for validation_job in validation_jobs:
    validation_fold = train_df[
        train_df["job_id"] == validation_job
    ].copy()

    # Fit TF-IDF only on the other training jobs
    fitting_fold = train_df[
        train_df["job_id"] != validation_job
    ].copy()

    tfidf_lojo_vectorizer = TfidfVectorizer(
        lowercase=True,
        stop_words="english"
    )

    tfidf_lojo_vectorizer.fit(
        pd.concat([
            fitting_fold["job_text"],
            fitting_fold["resume_text"]
        ])
    )

    scores = []

    for _, row in validation_fold.iterrows():
        job_vector = tfidf_lojo_vectorizer.transform(
            [row["job_text"]]
        )
        resume_vector = tfidf_lojo_vectorizer.transform(
            [row["resume_text"]]
        )

        score = cosine_similarity(
            job_vector,
            resume_vector
        )[0][0]

        scores.append(float(score))

    y_true = validation_fold["relevance_label"].to_numpy()

    ndcg = ndcg_score(
        [y_true],
        [np.array(scores)],
        k=5
    )

    ranking = validation_fold[
        ["candidate_id", "relevance_label"]
    ].copy()

    ranking["score"] = scores

    ranking = ranking.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    relevant_positions = ranking.index[
        ranking["relevance_label"] > 0
    ]

    mrr = (
        1.0 / (relevant_positions[0] + 1)
        if len(relevant_positions) > 0
        else 0.0
    )

    tfidf_lojo_results.append({
        "validation_job": validation_job,
        "NDCG@5": ndcg,
        "MRR": mrr
    })

tfidf_lojo_df = pd.DataFrame(tfidf_lojo_results)

print(tfidf_lojo_df.to_string(index=False))
print("\nMean LOJO NDCG@5:", f"{tfidf_lojo_df['NDCG@5'].mean():.4f}")
print("Mean LOJO MRR:", f"{tfidf_lojo_df['MRR'].mean():.4f}")

In [ ]:
from sentence_transformers import SentenceTransformer

semantic_model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
def calculate_semantic_similarity(job_text, resume_text):
    job_embedding = semantic_model.encode([job_text])
    resume_embedding = semantic_model.encode([resume_text])

    similarity = cosine_similarity(
        job_embedding,
        resume_embedding
    )[0][0]

    return float(similarity)

In [ ]:
semantic_lojo_results = []

for validation_job in validation_jobs:
    validation_fold = train_df[
        train_df["job_id"] == validation_job
    ].copy()

    scores = []

    for _, row in validation_fold.iterrows():
        score = calculate_semantic_similarity(
            row["job_text"],
            row["resume_text"]
        )
        scores.append(score)

    y_true = validation_fold["relevance_label"].to_numpy()

    ndcg = ndcg_score(
        [y_true],
        [np.array(scores)],
        k=5
    )

    ranking = validation_fold[
        ["candidate_id", "relevance_label"]
    ].copy()

    ranking["score"] = scores

    ranking = ranking.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    relevant_positions = ranking.index[
        ranking["relevance_label"] > 0
    ]

    mrr = (
        1.0 / (relevant_positions[0] + 1)
        if len(relevant_positions) > 0
        else 0.0
    )

    semantic_lojo_results.append({
        "validation_job": validation_job,
        "NDCG@5": ndcg,
        "MRR": mrr
    })

semantic_lojo_df = pd.DataFrame(semantic_lojo_results)

print(semantic_lojo_df.to_string(index=False))
print("\nMean LOJO NDCG@5:", f"{semantic_lojo_df['NDCG@5'].mean():.4f}")
print("Mean LOJO MRR:", f"{semantic_lojo_df['MRR'].mean():.4f}")

In [ ]:
structured_lojo_results = []

structured_feature_columns = [
    "required_skill_coverage",
    "preferred_skill_coverage",
    "experience_match",
    "education_match",
    "project_relevance",
    "certification_relevance"
]

for validation_job in validation_jobs:
    validation_fold = train_df[
        train_df["job_id"] == validation_job
    ].copy()

    scores = validation_fold[
        structured_feature_columns
    ].mean(axis=1).to_numpy()

    y_true = validation_fold["relevance_label"].to_numpy()

    ndcg = ndcg_score(
        [y_true],
        [np.array(scores)],
        k=5
    )

    ranking = validation_fold[
        ["candidate_id", "relevance_label"]
    ].copy()

    ranking["score"] = scores

    ranking = ranking.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    relevant_positions = ranking.index[
        ranking["relevance_label"] > 0
    ]

    mrr = (
        1.0 / (relevant_positions[0] + 1)
        if len(relevant_positions) > 0
        else 0.0
    )

    structured_lojo_results.append({
        "validation_job": validation_job,
        "NDCG@5": ndcg,
        "MRR": mrr
    })

structured_lojo_df = pd.DataFrame(structured_lojo_results)

print(structured_lojo_df.to_string(index=False))
print("\nMean LOJO NDCG@5:", f"{structured_lojo_df['NDCG@5'].mean():.4f}")
print("Mean LOJO MRR:", f"{structured_lojo_df['MRR'].mean():.4f}")

In [ ]:
lojo_comparison_df = pd.DataFrame({
    "Model": [
        "Keyword",
        "TF-IDF",
        "Structured",
        "Semantic",
        "XGBoost"
    ],
    "Mean_LOJO_NDCG@5": [
        keyword_lojo_df["NDCG@5"].mean(),
        tfidf_lojo_df["NDCG@5"].mean(),
        structured_lojo_df["NDCG@5"].mean(),
        semantic_lojo_df["NDCG@5"].mean(),
        0.9545
    ],
    "Mean_LOJO_MRR": [
        keyword_lojo_df["MRR"].mean(),
        tfidf_lojo_df["MRR"].mean(),
        structured_lojo_df["MRR"].mean(),
        semantic_lojo_df["MRR"].mean(),
        1.0000
    ]
})

lojo_comparison_df

In [ ]:
import os

model_dir = "/content/drive/MyDrive/AI_Resume_Screening/models"

print(os.listdir(model_dir))

In [ ]:
lojo_results_path = "/content/drive/MyDrive/AI_Resume_Screening/results/lojo_comparison.csv"

lojo_comparison_df.to_csv(
    lojo_results_path,
    index=False
)

print("Saved:", lojo_results_path)

In [ ]:
import os

model_dir = "/content/drive/MyDrive/AI_Resume_Screening/models"

print(os.listdir(model_dir))

In [ ]:
test_jobs = ["J002", "J005"]

xgb_test_results = []

for test_job in test_jobs:
    test_fold = test_df[
        test_df["job_id"] == test_job
    ].copy()

    X_test = test_fold[feature_columns].to_numpy()
    y_test = test_fold["relevance_label"].to_numpy()

    scores = ranker_v2.predict(X_test)

    ndcg = ndcg_score(
        [y_test],
        [np.array(scores)],
        k=5
    )

    ranking = test_fold[
        ["candidate_id", "relevance_label"]
    ].copy()

    ranking["score"] = scores

    ranking = ranking.sort_values(
        "score",
        ascending=False
    ).reset_index(drop=True)

    relevant_positions = ranking.index[
        ranking["relevance_label"] > 0
    ]

    mrr = (
        1.0 / (relevant_positions[0] + 1)
        if len(relevant_positions) > 0
        else 0.0
    )

    xgb_test_results.append({
        "test_job": test_job,
        "NDCG@5": ndcg,
        "MRR": mrr
    })

xgb_test_df = pd.DataFrame(xgb_test_results)

print(xgb_test_df.to_string(index=False))
print("\nMean Test NDCG@5:", f"{xgb_test_df['NDCG@5'].mean():.4f}")
print("Mean Test MRR:", f"{xgb_test_df['MRR'].mean():.4f}")

In [ ]:
final_test_results_path = "/content/drive/MyDrive/AI_Resume_Screening/results/xgboost_final_test_results.csv"

xgb_test_df.to_csv(
    final_test_results_path,
    index=False
)

print("Saved:", final_test_results_path)

In [ ]:
print(xgb_test_df.columns.tolist())
print()
print(xgb_test_df.head())

In [ ]:
print([name for name in globals() if "pred" in name.lower() or "rank" in name.lower()])

In [ ]:
print(type(predicted_scores))
print(predicted_scores)

In [ ]:
print(type(ranked_group))
print(ranked_group)

In [ ]:
xgb_9features_path = "/content/drive/MyDrive/AI_Resume_Screening/models/xgb_ranker_9features.json"

ranker_v2.save_model(xgb_9features_path)

print("Saved:", xgb_9features_path)

In [ ]:
final_ranking_path = "/content/drive/MyDrive/AI_Resume_Screening/results/xgboost_final_test_rankings.csv"

final_ranking_df = detailed_ranking.copy()

final_ranking_df.to_csv(
    final_ranking_path,
    index=False
)

print("Saved:", final_ranking_path)
print()
print(final_ranking_df.to_string(index=False))

In [ ]:
# Final candidate-level predictions for the untouched test jobs

final_ranking_df = test_df[
    ["job_id", "candidate_id", "relevance_label"] + feature_columns
].copy()

# Predict using the already-trained 9-feature XGBoost model
final_ranking_df["xgb_score"] = ranker_v2.predict(
    final_ranking_df[feature_columns].to_numpy()
)

# Rank candidates separately within each job
final_ranking_df = final_ranking_df.sort_values(
    ["job_id", "xgb_score"],
    ascending=[True, False]
).reset_index(drop=True)

final_ranking_df["rank"] = (
    final_ranking_df.groupby("job_id").cumcount() + 1
)

# Put the important columns first
final_ranking_df = final_ranking_df[
    ["job_id", "candidate_id", "rank", "xgb_score", "relevance_label"]
    + feature_columns
]

# Save
final_ranking_path = (
    "/content/drive/MyDrive/AI_Resume_Screening/results/"
    "xgboost_final_test_rankings.csv"
)

final_ranking_df.to_csv(
    final_ranking_path,
    index=False
)

print("Saved:", final_ranking_path)
print()
print(final_ranking_df.to_string(index=False))

In [ ]:
print("CURRENT NOTEBOOK STATE")
print("=" * 40)

variables_to_check = [
    "pairs",
    "pairs_structured",
    "labeled_pairs",
    "feature_df_v2",
    "feature_df_labeled_v2",
    "train_df",
    "test_df",
    "feature_columns",
    "ranker_v2",
    "final_ranking_df",
    "xgb_test_df",
]

for name in variables_to_check:
    if name in globals():
        obj = globals()[name]
        try:
            shape = obj.shape
            print(f"{name}: EXISTS | type={type(obj).__name__} | shape={shape}")
        except Exception:
            print(f"{name}: EXISTS | type={type(obj).__name__}")
    else:
        print(f"{name}: NOT DEFINED")

In [ ]:
print("Model type:", type(ranker_v2))
print("Number of features:", ranker_v2.n_features_in_)
print("Feature columns:")
print(feature_columns)

print("\nModel parameters:")
print(ranker_v2.get_params())